export default {
    FeatureName: 'M@S Studio ACOM Full Pricing Express Save',
    features: [
        {
            tcid: '0',
            name: '@studio-full-pricing-express-save-title-changes',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                title: 'Adobe Express Free',
                newTitle: 'Express Free Updated',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '1',
            name: '@studio-full-pricing-express-save-price-changes',
            path: '/studio.html',
            data: {
                cardid: 'a7f68812-0fb3-42f9-a8d4-f28e3f1dd6d4',
                price: 'US$9.99/mo',
                newPrice: 'US$12.99/mo',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '2',
            name: '@studio-full-pricing-express-save-body-changes',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                body: 'Quick actions and templates to get started.',
                newBody: 'Updated body text for testing persistence.',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '3',
            name: '@studio-full-pricing-express-save-shortDescription-changes',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                shortDescription: 'Additional details about the product.',
                newShortDescription: 'Updated additional details for save testing.',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '4',
            name: '@studio-full-pricing-express-save-cta-changes',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                ctaText: 'Start for free',
                newCtaText: 'Try now for free',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '5',
            name: '@studio-full-pricing-express-save-badge-changes',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                badge: 'Pro',
                newBadge: 'Premium Pro',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '6',
            name: '@studio-full-pricing-express-save-mnemonic-changes',
            path: '/studio.html',
            data: {
                cardid: 'a7f68812-0fb3-42f9-a8d4-f28e3f1dd6d4',
                mnemonicField: 'https://www.adobe.com/content/dam/shared/images/product-icons/svg/express.svg',
                newMnemonicField: 'https://www.adobe.com/content/dam/shared/images/product-icons/svg/firefly.svg',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '7',
            name: '@studio-full-pricing-express-save-divider-changes',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '8',
            name: '@studio-full-pricing-express-save-multiple-changes',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                title: 'Adobe Express Free',
                newTitle: 'Express Premium Edition',
                body: 'Quick actions and templates to get started.',
                newBody: 'Advanced tools and premium templates.',
                ctaText: 'Start for free',
                newCtaText: 'Get Premium Now',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '9',
            name: '@studio-full-pricing-express-save-validation-success',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                title: 'Adobe Express Free',
                newTitle: 'Save Validation Test',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
    ],
};
