export default {
    FeatureName: 'M@S Studio ACOM Full Pricing Express',
    features: [
        // Note: Variant change test removed - we don't want to change card variants during testing
        {
            tcid: '1',
            name: '@studio-full-pricing-express-edit-size',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '2',
            name: '@studio-full-pricing-express-edit-title',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                title: 'Adobe Express Free',
                newTitle: 'Express Free Updated',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '3',
            name: '@studio-full-pricing-express-edit-title-mnemonic',
            path: '/studio.html',
            data: {
                cardid: 'a7f68812-0fb3-42f9-a8d4-f28e3f1dd6d4',
                mnemonicField: 'https://www.adobe.com/content/dam/shared/images/product-icons/svg/express.svg',
                newMnemonicField: 'https://www.adobe.com/content/dam/shared/images/product-icons/svg/photoshop.svg',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '4',
            name: '@studio-full-pricing-express-edit-price',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                price: 'Free',
                newPrice: 'US$0.00/mo',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '5',
            name: '@studio-full-pricing-express-edit-osi',
            path: '/studio.html',
            data: {
                cardid: 'a7f68812-0fb3-42f9-a8d4-f28e3f1dd6d4',
                osi: 'test-osi-1',
                offerTypeTag: 'offer_type/base',
                marketSegmentsTag: 'market_segments/com',
                planTypeTag: 'plan_type/m2m',
                newosi: 'test-osi-2',
                newPlanTypeTag: 'plan_type/puf',
                newOfferTypeTag: 'offer_type/trial',
                newMarketSegmentsTag: 'market_segments/edu',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '6',
            name: '@studio-full-pricing-express-edit-body',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                body: 'Quick actions and templates to get started.',
                newBody: 'Updated body text for testing.',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '7',
            name: '@studio-full-pricing-express-edit-shortDescription',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                shortDescription: 'Additional details about the product.',
                newShortDescription: 'Updated additional details for testing.',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '8',
            name: '@studio-full-pricing-express-edit-cta',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                ctaText: 'Start for free',
                newCtaText: 'Try now',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '9',
            name: '@studio-full-pricing-express-edit-divider-insertion',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '10',
            name: '@studio-full-pricing-express-edit-divider-removal',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '11',
            name: '@studio-full-pricing-express-edit-badge',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                badge: 'Pro',
                newBadge: 'Premium',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '12',
            name: '@studio-full-pricing-express-edit-badge-color',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                color: 'Yellow 300',
                newColor: 'Green 900',
                newColorCSS: 'rgb(5, 131, 78)',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '13',
            name: '@studio-full-pricing-express-edit-gradient-border',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                gradientBorder: true,
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '14',
            name: '@studio-full-pricing-express-edit-phone-number',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                phoneNumber: '1234567890',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '15',
            name: '@studio-full-pricing-express-edit-cta-variant',
            path: '/studio.html',
            data: {
                cardid: 'a7f68812-0fb3-42f9-a8d4-f28e3f1dd6d4',
                osi: 'test-osi-1',
                variant: 'accent',
                ctaCSS: {
                    'background-color': 'rgb(59, 99, 251)',
                    color: 'rgb(255, 255, 255)',
                },
                newCtaCSS: {
                    color: 'rgb(44, 44, 44)',
                },
                newVariant: 'primary-outline',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '16',
            name: '@studio-full-pricing-express-edit-cta-checkout-params',
            path: '/studio.html',
            data: {
                cardid: 'a7f68812-0fb3-42f9-a8d4-f28e3f1dd6d4',
                osi: 'test-osi-1',
                checkoutParams: {
                    mv: '1',
                    promoid: 'ABC123',
                    mv2: '2',
                },
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '17',
            name: '@studio-full-pricing-express-edit-price-promo',
            path: '/studio.html',
            data: {
                cardid: 'a7f68812-0fb3-42f9-a8d4-f28e3f1dd6d4',
                promo: 'TESTPROMO123',
                newPromo: 'NEWPROMO456',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '18',
            name: '@studio-full-pricing-express-edit-cta-promo',
            path: '/studio.html',
            data: {
                cardid: 'a7f68812-0fb3-42f9-a8d4-f28e3f1dd6d4',
                promo: 'CTAPROMO123',
                newPromo: 'NEWCTAPROMO456',
                ucv3: 'commerce.adobe.com/store/email',
                country: 'US',
                ctx: 'fp',
                lang: 'en',
                client: 'adobe_com',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '19',
            name: '@studio-full-pricing-express-edit-mnemonic-size-xs',
            path: '/studio.html',
            data: {
                cardid: 'a7f68812-0fb3-42f9-a8d4-f28e3f1dd6d4',
                mnemonicField: 'https://www.adobe.com/content/dam/shared/images/product-icons/svg/express.svg',
                mnemonicSize: 'xs',
                mnemonicText: 'Express',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '20',
            name: '@studio-full-pricing-express-edit-mnemonic-size-s',
            path: '/studio.html',
            data: {
                cardid: 'a7f68812-0fb3-42f9-a8d4-f28e3f1dd6d4',
                mnemonicField: 'https://www.adobe.com/content/dam/shared/images/product-icons/svg/photoshop.svg',
                mnemonicSize: 's',
                mnemonicText: 'Photoshop',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '21',
            name: '@studio-full-pricing-express-edit-mnemonic-size-m',
            path: '/studio.html',
            data: {
                cardid: 'a7f68812-0fb3-42f9-a8d4-f28e3f1dd6d4',
                mnemonicField: 'https://www.adobe.com/content/dam/shared/images/product-icons/svg/illustrator.svg',
                mnemonicSize: 'm',
                mnemonicText: 'Illustrator',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '22',
            name: '@studio-full-pricing-express-edit-mnemonic-size-l',
            path: '/studio.html',
            data: {
                cardid: 'a7f68812-0fb3-42f9-a8d4-f28e3f1dd6d4',
                mnemonicField: 'https://www.adobe.com/content/dam/shared/images/product-icons/svg/indesign.svg',
                mnemonicSize: 'l',
                mnemonicText: 'InDesign',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '23',
            name: '@studio-full-pricing-express-edit-mnemonic-size-change',
            path: '/studio.html',
            data: {
                cardid: 'a7f68812-0fb3-42f9-a8d4-f28e3f1dd6d4',
                mnemonicField: 'https://www.adobe.com/content/dam/shared/images/product-icons/svg/acrobat.svg',
                initialSize: 'xs',
                newSize: 'l',
                mnemonicText: 'Acrobat',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '24',
            name: '@studio-full-pricing-express-edit-collection-layout',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                layout: 'grid',
                columns: 3,
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '25',
            name: '@studio-full-pricing-express-edit-compare-feature',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                compareText: 'Compare plans',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
        {
            tcid: '26',
            name: '@studio-full-pricing-express-edit-divider',
            path: '/studio.html',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                dividerStyle: 'solid',
            },
            browserParams: '#query=',
            tags: '@studio-full-pricing-express @mas-studio @express',
        },
    ],
};
