export default {
    FeatureName: 'M@S Studio Full Pricing Express Workflow Tests',
    features: [
        {
            tcid: '0',
            name: '@Full-Pricing-Express-Workflow-Text-Fields',
            path: '/studio.html',
            browserParams: '#query=',
            tags: '@studio-full-pricing-express-workflow-text-fields',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                title: 'Adobe Express Free',
                newTitle: 'Updated Express Title',
                badge: 'Most Popular',
                newBadge: 'BEST VALUE',
                mnemonicField: 'https://www.adobe.com/icons/express.svg',
            },
        },
        {
            tcid: '1',
            name: '@Full-Pricing-Express-Workflow-Price-OSI',
            path: '/studio.html',
            browserParams: '#query=',
            tags: '@studio-full-pricing-express-workflow-price-osi',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                price: 'US$31.49/mo',
                newPrice: 'US$31.49/mo',
                osi: 'M59ZAPQXQM3TPPQQ',
                newosi: 'M59ZAPQXQM3TPPQQ',
                offerTypeTag: 'TRIAL',
                marketSegmentsTag: 'COM',
                planTypeTag: 'ABM',
                newPlanTypeTag: 'M2M',
                newOfferTypeTag: 'BASE',
                newMarketSegmentsTag: 'EDU',
            },
        },
        {
            tcid: '2',
            name: '@Full-Pricing-Express-Workflow-CTA',
            path: '/studio.html',
            browserParams: '#query=',
            tags: '@studio-full-pricing-express-workflow-cta',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                ctaText: 'Buy now',
                newCtaText: 'Get Started',
                variant: 'primary-link',
                newVariant: 'accent',
                checkoutParams: {
                    mv: 'mv2',
                    promoid: 'PROMO123',
                    mv2: 'mv2value',
                },
                phoneNumber: '1-800-123-4567',
                osi: 'A9E97T89AZ2A8N7R',
            },
        },
        {
            tcid: '5',
            name: '@Full-Pricing-Express-Workflow-Multiple-Changes',
            path: '/studio.html',
            browserParams: '#query=',
            tags: '@studio-full-pricing-express-workflow-multiple-changes',
            data: {
                cardid: '9406f1ae-7bee-48c3-9892-49af6816033e',
                title: 'Original Title',
                newTitle: 'All Changes Title',
                body: 'Original body text',
                newBody: 'Updated body with all changes applied',
                badge: 'Original',
                newBadge: 'UPDATED',
                ctaText: 'Original CTA',
                newCtaText: 'Updated CTA Text',
            },
        },
    ],
};
