application:
  actions: actions
  web: web-src
  hooks:
    test: npm run test
  runtimeManifest:
    packages:
      MerchAtScaleStudio:
        license: Apache-2.0
        actions:
          updateMembers:
            function: src/members/update.js
            web: "yes"
            runtime: nodejs:22
            annotations:
              require-adobe-auth: true
              final: false

          listMembers:
            function: src/members/list.js
            web: "yes"
            runtime: nodejs:22
            inputs:
              IMS_CLIENT_ID: $IMS_CLIENT_ID
