/**
 * Generate Vector Embeddings for Knowledge Chunks
 *
 * Processes all knowledge chunks through Amazon Titan Embed Text v1
 * and writes the results to a JS module for in-memory vector search.
 *
 * Usage: AWS_ACCESS_KEY_ID=... AWS_SECRET_ACCESS_KEY=... AWS_REGION=... node scripts/generate-vectors.js
 */

import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { KNOWLEDGE_CHUNKS } from '../src/index-docs/embedded-chunks.js';
import { EmbeddingsClient } from '../src/shared/embeddings-client.js';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const outputPath = join(scriptDir, '..', 'src', 'shared', 'embedded-vectors.js');

async function generateVectors() {
    const { AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION } = process.env;

    if (!AWS_ACCESS_KEY_ID || !AWS_SECRET_ACCESS_KEY) {
        console.error('Missing required environment variables: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY');
        process.exit(1);
    }

    const client = new EmbeddingsClient({
        accessKeyId: AWS_ACCESS_KEY_ID,
        secretAccessKey: AWS_SECRET_ACCESS_KEY,
        region: AWS_REGION || 'us-west-2',
    });

    console.log(`Processing ${KNOWLEDGE_CHUNKS.length} chunks...`);

    const chunksWithVectors = [];

    for (let i = 0; i < KNOWLEDGE_CHUNKS.length; i++) {
        const chunk = KNOWLEDGE_CHUNKS[i];
        const vector = await client.embed(chunk.text);

        chunksWithVectors.push({
            id: chunk.id,
            text: chunk.text,
            metadata: chunk.metadata,
            vector,
        });

        if ((i + 1) % 10 === 0) {
            console.log(`  Embedded ${i + 1}/${KNOWLEDGE_CHUNKS.length}`);
        }
    }

    console.log(`All ${KNOWLEDGE_CHUNKS.length} chunks embedded. Writing output...`);

    const header = [
        '/**',
        ' * Knowledge Chunks with Pre-computed Vector Embeddings',
        ' *',
        ` * Generated at: ${new Date().toISOString()}`,
        ` * Total chunks: ${chunksWithVectors.length}`,
        ' * Vector dimensions: 1536 (Amazon Titan Embed Text v1)',
        ' *',
        ' * Generated by: node scripts/generate-vectors.js',
        ' */',
        '',
    ].join('\n');

    const content = `${header}export const CHUNKS_WITH_VECTORS = ${JSON.stringify(chunksWithVectors, null, 2)};\n`;

    writeFileSync(outputPath, content, 'utf-8');
    console.log(`Written to ${outputPath} (${(Buffer.byteLength(content) / 1024 / 1024).toFixed(1)}MB)`);
}

generateVectors().catch((error) => {
    console.error('Failed to generate vectors:', error.message);
    process.exit(1);
});
