/**
 * GENERATED FILE — do not edit by hand.
 * Source: src/ai-chat/knowledge/*.md — regenerate with `npm run build:knowledge`.
 * The corpus sync test fails when this file is out of date.
 */

export const KNOWLEDGE_CHUNKS = [
    {
        "id": "bulk-operations.md#0",
        "topic": "bulk-operations",
        "title": "Bulk Operations in MAS Studio",
        "section": "Can the AI assistant update or publish many cards at once?",
        "keywords": [
            "bulk",
            "bulk update",
            "bulk publish",
            "bulk unpublish",
            "publish multiple",
            "batch",
            "mass update",
            "find and replace",
            "preview"
        ],
        "text": "No. The assistant does not run bulk updates or bulk publishes, and it has no\noperation for either. Bulk work happens in Studio itself, which has a purpose\nbuilt UI for it with preview, snapshot and revert. If you ask the assistant to\nchange or publish a set of cards, it points you here rather than attempting it.\n\nFor a handful of cards, ask for them one at a time: a single card update or\npublish is still something the assistant does, each with its own confirmation."
    },
    {
        "id": "bulk-operations.md#1",
        "topic": "bulk-operations",
        "title": "Bulk Operations in MAS Studio",
        "section": "How do I update many cards at once in Studio?",
        "keywords": [
            "bulk",
            "bulk update",
            "bulk publish",
            "bulk unpublish",
            "publish multiple",
            "batch",
            "mass update",
            "find and replace",
            "preview"
        ],
        "text": "Use the Select button in the Fragments toolbar to multi-select cards, then apply\nthe change to the selection. For large batches, use a bulk publish project under\nAdvanced tools."
    },
    {
        "id": "bulk-operations.md#2",
        "topic": "bulk-operations",
        "title": "Bulk Operations in MAS Studio",
        "section": "What is the Bulk Publishing page in Studio?",
        "keywords": [
            "bulk",
            "bulk update",
            "bulk publish",
            "bulk unpublish",
            "publish multiple",
            "batch",
            "mass update",
            "find and replace",
            "preview"
        ],
        "text": "Studio has a bulk publishing feature built around bulk publish projects, reached\nfrom Advanced tools in the side navigation. A saved project holds a list of\nfragment paths and target locales; its items are picked with an items selector\nspanning cards, collections, and placeholders, and items already in the project\nare skipped with a warning. Publishing a project dispatches an asynchronous\nbackend worker (the request is accepted immediately and runs in the background)\nthat resolves every path in every selected locale, takes a snapshot of the\ncurrent published state, and then publishes the resolved fragments. The project\nends in one of three statuses: Published, Partially published, or Failed.\nFragments that do not exist in a target locale are reported as not localized\nrather than failing silently. Because a snapshot is taken before publishing, a\nbulk publish can be reverted, and Studio checks whether entries were modified\nafter the snapshot before allowing a revert."
    },
    {
        "id": "bulk-operations.md#3",
        "topic": "bulk-operations",
        "title": "Bulk Operations in MAS Studio",
        "section": "Can I bulk delete cards?",
        "keywords": [
            "bulk",
            "bulk update",
            "bulk publish",
            "bulk unpublish",
            "publish multiple",
            "batch",
            "mass update",
            "find and replace",
            "preview"
        ],
        "text": "No. Deletion is not performed by the assistant at all, in bulk or one at a time.\nIf you ask to delete cards, the assistant declines and directs you to MAS Studio,\nwhere fragments are deleted individually through the UI with a confirmation\ndialog. This is a deliberate safety restriction: deletion is destructive and\ncannot be previewed and approved the way an edit can."
    },
    {
        "id": "bulk-operations.md#4",
        "topic": "bulk-operations",
        "title": "Bulk Operations in MAS Studio",
        "section": "How do I see the cards from my last search?",
        "keywords": [
            "bulk",
            "bulk update",
            "bulk publish",
            "bulk unpublish",
            "publish multiple",
            "batch",
            "mass update",
            "find and replace",
            "preview"
        ],
        "text": "Ask the assistant \"show me those cards again\" or \"list the cards from our last\nsearch\". It renders the cards referenced by the previous operation, using the\nfragment IDs stored in the conversation context. If there is no previous\noperation in the conversation, it tells you so rather than guessing. Fragment IDs\nare AEM UUIDs and cannot be derived from card titles, so the assistant never\ninvents them."
    },
    {
        "id": "cards-and-publishing.md#0",
        "topic": "cards",
        "title": "Cards and Publishing in MAS Studio",
        "section": "How do I create a card in MAS Studio?",
        "keywords": [
            "card",
            "merch card",
            "variant",
            "create card",
            "publish",
            "unpublish",
            "edit fields",
            "draft",
            "modified",
            "surface"
        ],
        "text": "Open MAS Studio at https://mas.adobe.com/studio.html, use the folder picker in the top navigation to choose the surface and folder where the card should live, and click Create, which offers the available content types: merch card, collection, and compare chart. The create dialog asks for a title — and for a merch card, an offer chosen through the Offer Selector Tool, unless the folder's template is offerless. After creation the card opens in the editor panel, where you choose the variant and fill in the fields: title, description, prices, CTAs, and optional extras such as a badge, mnemonics (product icons), or a background image. The editor shows a live preview as you type. Saving stores the card as a content fragment in Draft status; it is not visible to end users until you publish it. You can also describe the card you want to the AI assistant in the chat panel, or duplicate an existing card and edit the copy — the assistant can duplicate a card for you if you give it the card ID."
    },
    {
        "id": "cards-and-publishing.md#1",
        "topic": "cards",
        "title": "Cards and Publishing in MAS Studio",
        "section": "Which card variants exist and which surfaces use them?",
        "keywords": [
            "card",
            "merch card",
            "variant",
            "create card",
            "publish",
            "unpublish",
            "edit fields",
            "draft",
            "modified",
            "surface"
        ],
        "text": "Each surface supports a specific set of card variants. Adobe.com (acom) uses plans, plans-students, plans-education, catalog, special-offers, mini, and simplified-pricing-express. Creative Cloud Desktop (ccd) uses ccd-slice and ccd-suggested. The commerce surface (Unified Checkout) uses fries, a horizontal commerce-focused card. Adobe Home uses ah-try-buy-widget and ah-promoted-plans. Adobe Express uses full-pricing-express and simplified-pricing-express. Variants differ in layout, required fields, and CTA styling: plans cards require a title, prices, and CTAs and use primary-outline CTAs, while fries cards require a title, description, and CTAs and use primary CTAs. Choose the variant first, because it determines which fields the editor offers."
    },
    {
        "id": "cards-and-publishing.md#2",
        "topic": "cards",
        "title": "Cards and Publishing in MAS Studio",
        "section": "What is a surface and how does it affect my card?",
        "keywords": [
            "card",
            "merch card",
            "variant",
            "create card",
            "publish",
            "unpublish",
            "edit fields",
            "draft",
            "modified",
            "surface"
        ],
        "text": "A surface is a destination where merch cards render: acom (adobe.com pages), ccd (Creative Cloud Desktop), commerce (Unified Checkout), adobe-home (Adobe Home), and express (Adobe Express). There is also a sandbox area for testing. Card content is stored under the /content/dam/mas/ path in AEM, organized into folders per surface, so the folder where you create a card determines its surface, and the surface determines which variants are valid. The AI assistant detects the surface from the folder you are currently browsing and suggests matching variants, and card searches can be filtered by surface and locale."
    },
    {
        "id": "cards-and-publishing.md#3",
        "topic": "cards",
        "title": "Cards and Publishing in MAS Studio",
        "section": "How do I publish a card?",
        "keywords": [
            "card",
            "merch card",
            "variant",
            "create card",
            "publish",
            "unpublish",
            "edit fields",
            "draft",
            "modified",
            "surface"
        ],
        "text": "Open the card in the editor, make sure there are no validation errors and all required fields for the variant are filled, then use the Publish action and confirm. The card status changes from Draft to Published and the fragment becomes available to consuming pages through the delivery API. Publishing also publishes the card's referenced fragments that are still in draft or unpublished status, so dependencies go live together. To publish many items at once, use a bulk publish project under Advanced tools, or ask the AI assistant. The AI assistant can publish a card if you ask (for example \"publish this card\"); it always asks for your confirmation before publishing, and for multiple cards it can first show a preview of exactly which cards would be affected before running the job."
    },
    {
        "id": "cards-and-publishing.md#4",
        "topic": "cards",
        "title": "Cards and Publishing in MAS Studio",
        "section": "How do I search and filter cards?",
        "keywords": [
            "card",
            "merch card",
            "variant",
            "create card",
            "publish",
            "unpublish",
            "edit fields",
            "draft",
            "modified",
            "surface"
        ],
        "text": "The Fragments page has a text search plus a filter panel with facets for template, market segment, customer segment, product, offer type, plan type, personalization (pzn) tags, arbitrary tags, and status. The locale you are browsing comes from the locale picker in the top navigation, and the surface and folder come from the folder picker next to it. A personalization toggle hides or shows grouped-variation content in the list. The AI assistant can run the same searches conversationally, including by linked offer ID."
    },
    {
        "id": "cards-and-publishing.md#5",
        "topic": "cards",
        "title": "Cards and Publishing in MAS Studio",
        "section": "What happens when I edit a card that is already published?",
        "keywords": [
            "card",
            "merch card",
            "variant",
            "create card",
            "publish",
            "unpublish",
            "edit fields",
            "draft",
            "modified",
            "surface"
        ],
        "text": "Cards have three statuses in Studio: Draft, Published, and Modified. When you edit and save a card that was already published, its status becomes Modified, meaning it has unpublished changes. Publish the card again so the live version picks up your edits. The status indicator in the content table shows where each card stands: Draft (never published), Published (live and unchanged), or Modified (live but with pending changes). Save with the Save button or Ctrl+S; the editor tracks unsaved changes and prompts before you close or navigate away, and Version History lets you inspect earlier versions of the fragment."
    },
    {
        "id": "cards-and-publishing.md#6",
        "topic": "cards",
        "title": "Cards and Publishing in MAS Studio",
        "section": "How do I unpublish a card and what happens to pages using it?",
        "keywords": [
            "card",
            "merch card",
            "variant",
            "create card",
            "publish",
            "unpublish",
            "edit fields",
            "draft",
            "modified",
            "surface"
        ],
        "text": "Unpublishing removes a card from delivery, so any live page that references the fragment stops rendering it. Typical reasons to unpublish are an ended promotion, outdated content, or deprecating a card. Open the card and use the Unpublish action, or select several cards and unpublish in bulk. The AI assistant can unpublish a single card or a batch of cards by ID; because this changes production it always asks you to confirm first. After unpublishing, remember to update any pages that referenced the card."
    },
    {
        "id": "cards-and-publishing.md#7",
        "topic": "cards",
        "title": "Cards and Publishing in MAS Studio",
        "section": "Can the AI assistant edit cards for me?",
        "keywords": [
            "card",
            "merch card",
            "variant",
            "create card",
            "publish",
            "unpublish",
            "edit fields",
            "draft",
            "modified",
            "surface"
        ],
        "text": "Yes. The assistant can update fields on a single card, run a bulk update across many cards (including text replacements), duplicate a card, open a card in the Studio editor for you, and copy a deep link to a card. Before any bulk update it can show a dry-run preview of exactly what would change on each card, and every change requires your explicit confirmation before it runs. It can also search cards by title, content, tags, surface, locale, or linked offer ID, and fetch a card's full contents when you just want to read it."
    },
    {
        "id": "cards-and-publishing.md#8",
        "topic": "cards",
        "title": "Cards and Publishing in MAS Studio",
        "section": "How do locale variations of a card work?",
        "keywords": [
            "card",
            "merch card",
            "variant",
            "create card",
            "publish",
            "unpublish",
            "edit fields",
            "draft",
            "modified",
            "surface"
        ],
        "text": "A card has a locale-default parent fragment, and each locale can have exactly one variation of it — attempting to create a second variation for the same locale fails. Variations carry translated or region-specific content while staying linked to the parent. The AI assistant can show a card's full variation tree, list which locales already have variations, find the parent of a variation, and create a new locale variation of a card (with confirmation). To find gaps, ask it to list cards that are missing a variation for a target locale."
    },
    {
        "id": "headless-and-fields.md#0",
        "topic": "headless",
        "title": "Headless cards and single fields (mas-field)",
        "section": "What is mas-field?",
        "keywords": [
            "mas-field",
            "headless",
            "field",
            "single field",
            "inline",
            "copy field",
            "field link",
            "embed",
            "reuse",
            "one field",
            "price inline",
            "cta inline",
            "headless variant",
            "consumer page",
            "autoblock",
            "jsonld"
        ],
        "text": "mas-field renders exactly one authored field of one card fragment, inline in page copy, with no card around it. There is no border, no badge, no slots and no variant layout: just that field's value. It exists for cases like putting a card's price in the middle of a marquee headline, or its CTA in a paragraph of body copy. The markup on a consumer page looks like a mas-field element with a field attribute naming the field, wrapping an aem-fragment element that names the fragment id. The rendered value lands in a span marked with the data-role mas-field-content. Use it when the fragment is the source of truth for a price, CTA or label, but a whole card is not wanted in that spot."
    },
    {
        "id": "headless-and-fields.md#1",
        "topic": "headless",
        "title": "Headless cards and single fields (mas-field)",
        "section": "What does headless mean in MAS? It means two different things",
        "keywords": [
            "mas-field",
            "headless",
            "field",
            "single field",
            "inline",
            "copy field",
            "field link",
            "embed",
            "reuse",
            "one field",
            "price inline",
            "cta inline",
            "headless variant",
            "consumer page",
            "autoblock",
            "jsonld"
        ],
        "text": "These are separate features and it matters which one is meant. First, mas-field is a headless usage of a card fragment: any fragment, any template, one field at a time, rendered on a consumer page without a card. Second, headless is also the name of a card variant, a Studio template that renders the fragment as a labelled list of all its fields (Title, Product price, CTAs and so on) instead of a designed card. The headless variant is a card-shaped inspector or feed view, authored in Studio like any other template and available on the sandbox, acom-cc and acom-dc surfaces. Short version: mas-field is the consumer-page mechanism, the headless variant is a Studio template."
    },
    {
        "id": "headless-and-fields.md#2",
        "topic": "headless",
        "title": "Headless cards and single fields (mas-field)",
        "section": "How do I use one field of a card on a page?",
        "keywords": [
            "mas-field",
            "headless",
            "field",
            "single field",
            "inline",
            "copy field",
            "field link",
            "embed",
            "reuse",
            "one field",
            "price inline",
            "cta inline",
            "headless variant",
            "consumer page",
            "autoblock",
            "jsonld"
        ],
        "text": "Open the fragment in Studio and use the Copy Field button in the side rail. It lists every non-empty field with a live preview of its value, and copies a link whose text reads \"mas-field:\" followed by the folder path and the field name. Paste that link into the consumer page document. Milo's merch-card autoblock recognises the link and replaces it with the mas-field markup, so the author never writes the element by hand. The Copy Field button is the supported path; hand-writing a field link is easy to get wrong."
    },
    {
        "id": "headless-and-fields.md#3",
        "topic": "headless",
        "title": "Headless cards and single fields (mas-field)",
        "section": "Which field names can mas-field address?",
        "keywords": [
            "mas-field",
            "headless",
            "field",
            "single field",
            "inline",
            "copy field",
            "field link",
            "embed",
            "reuse",
            "one field",
            "price inline",
            "cta inline",
            "headless variant",
            "consumer page",
            "autoblock",
            "jsonld"
        ],
        "text": "A plain field name renders that whole field: prices, description, title, cardTitle, subtitle, shortDescription, promoText, callout and so on. A single-paragraph rich text field is unwrapped so it sits inline rather than starting a new block. The name ctas renders all CTAs as real checkout buttons in a footer slot, styled the way the card would style them. A numeric index like ctas[1] or ctas[2] renders only the Nth CTA, counting from 1, with the class attribute stripped so the host page can restyle it. An index can instead be a CTA's data-key, which is stable when CTAs are reordered, or a custom field's label, as in customFields[My Label]. The special name jsonLdSchema injects JSON-LD structured data instead of visible content."
    },
    {
        "id": "headless-and-fields.md#4",
        "topic": "headless",
        "title": "Headless cards and single fields (mas-field)",
        "section": "Does a single field still get the right price, promo and locale?",
        "keywords": [
            "mas-field",
            "headless",
            "field",
            "single field",
            "inline",
            "copy field",
            "field link",
            "embed",
            "reuse",
            "one field",
            "price inline",
            "cta inline",
            "headless variant",
            "consumer page",
            "autoblock",
            "jsonld"
        ],
        "text": "Yes, and this is the reason to use mas-field rather than copying a value into the page. It runs the same data pipeline as a card, so hosted prices resolve with the same locale defaults and the tax or per-unit labelling for that market appears as it would on a card. The fragment's promo code is applied to both prices and checkout URLs under the same compatibility rules a card uses, so older fragments are unaffected, and the promo code is stamped onto the CTA anchor itself so it survives Milo unwrapping the element. Card settings are honoured: hideTrialCTAs drops trial CTAs, displayPlanType drives the plan type on a legal price template, and displayAnnual is respected. Rich text tooltips get the Milo info glyph with correct placement, because Milo does not decorate mas-field content itself."
    },
    {
        "id": "headless-and-fields.md#5",
        "topic": "headless",
        "title": "Headless cards and single fields (mas-field)",
        "section": "How is mas-field different from a merch-card?",
        "keywords": [
            "mas-field",
            "headless",
            "field",
            "single field",
            "inline",
            "copy field",
            "field link",
            "embed",
            "reuse",
            "one field",
            "price inline",
            "cta inline",
            "headless variant",
            "consumer page",
            "autoblock",
            "jsonld"
        ],
        "text": "Same fragment, same data pipeline, same option providers, same promo and settings rules. The difference is scope: merch-card maps every field onto the slots of its variant layout, and mas-field renders one field with no layout at all. Anything that belongs to a variant layout, such as badge placement, whats-included, addons or slot height syncing, is out of scope for mas-field by design. A mas:ready event fires once the field has loaded and rendered, so a host block can decorate a CTA that resolved after the block itself ran. One known difference: merch-card also drops CTAs whose resolved offer type is a trial, while mas-field matches only the static trial allowlist."
    },
    {
        "id": "offers-and-ost.md#0",
        "topic": "offers",
        "title": "Offers and the Offer Selector Tool (OST)",
        "section": "What is the difference between a card and an offer?",
        "keywords": [
            "offer",
            "OSI",
            "offer selector",
            "OST",
            "price",
            "AOS",
            "product",
            "link offer",
            "arrangement code"
        ],
        "text": "A card is a content fragment authored in MAS Studio: the text, images, badges, and CTAs that users see. An offer is a commerce entity in Adobe's offer catalog (AOS) that defines a purchasable thing: the product, price, commitment, term, and customer segment. Cards never hardcode prices; instead a card stores an Offer Selector ID (OSI) that points at an offer. When the card renders on a page, the merch-card web component uses the OSI to fetch the current price from Adobe's Web Commerce Service (WCS) for the user's locale. If the price changes in the catalog, cards show the new price automatically without any re-authoring."
    },
    {
        "id": "offers-and-ost.md#1",
        "topic": "offers",
        "title": "Offers and the Offer Selector Tool (OST)",
        "section": "What is an OSI (Offer Selector ID)?",
        "keywords": [
            "offer",
            "OSI",
            "offer selector",
            "OST",
            "price",
            "AOS",
            "product",
            "link offer",
            "arrangement code"
        ],
        "text": "An OSI is the identifier stored on a card that selects its offer. It is a string of 7 to 64 characters made of letters, digits, underscores, and hyphens. An OSI is locale-agnostic: the same OSI works across all locales where the offer is valid, and currency, tax labels, and formatting are resolved automatically for the page's locale. An OSI is not the same thing as a raw offer ID, which is a 32-character hexadecimal string identifying one specific offer in AOS. The AI assistant can resolve an OSI to its underlying offer details, and can also fetch a single offer directly by its 32-character hex offer ID."
    },
    {
        "id": "offers-and-ost.md#2",
        "topic": "offers",
        "title": "Offers and the Offer Selector Tool (OST)",
        "section": "What is the Offer Selector Tool (OST)?",
        "keywords": [
            "offer",
            "OSI",
            "offer selector",
            "OST",
            "price",
            "AOS",
            "product",
            "link offer",
            "arrangement code"
        ],
        "text": "OST is Studio's built-in tool for finding an offer and attaching it to a card. Open it from the Offer Selector ID field in the card editor, search by product name, and narrow results by customer segment (individual, team, student), commitment, and term (monthly, annual). Selecting an offer inserts its OSI into the card; save the card afterwards so the OSI persists. OST also opens from the price and CTA fields in the card editor — selecting an offer there inserts an inline price or a checkout link into the field at the cursor. In release flows OST can open in a multi-select mode that picks a base offer and a trial offer together. The AI assistant can open OST for you on request, optionally pre-filled with search parameters."
    },
    {
        "id": "offers-and-ost.md#3",
        "topic": "offers",
        "title": "Offers and the Offer Selector Tool (OST)",
        "section": "How do I link an offer to a card?",
        "keywords": [
            "offer",
            "OSI",
            "offer selector",
            "OST",
            "price",
            "AOS",
            "product",
            "link offer",
            "arrangement code"
        ],
        "text": "In the editor, open OST from the OSI field, pick the offer, insert it, and save the card. Alternatively, ask the AI assistant to link a card to an offer by giving it the card ID and the OSI; it confirms with you before making the change. After linking, the assistant can validate card-offer consistency: it checks that the card's tags (plan type, offer type, customer segment) agree with the linked offer and reports any mismatches."
    },
    {
        "id": "offers-and-ost.md#4",
        "topic": "offers",
        "title": "Offers and the Offer Selector Tool (OST)",
        "section": "How do I find offers or products without opening OST?",
        "keywords": [
            "offer",
            "OSI",
            "offer selector",
            "OST",
            "price",
            "AOS",
            "product",
            "link offer",
            "arrangement code"
        ],
        "text": "Ask the AI assistant. It can search the AOS offer catalog with filters such as product arrangement code, commitment, term, customer segment, market segment, offer type, country, locale, and price point. It can list Adobe products from the catalog and search them by name, fetch a single product by its exact product arrangement (PA) code, and compare all plan types available for one product arrangement side by side. These are read-only lookups, so no confirmation is needed."
    },
    {
        "id": "offers-and-ost.md#5",
        "topic": "offers",
        "title": "Offers and the Offer Selector Tool (OST)",
        "section": "Can the AI assistant create a new offer selector?",
        "keywords": [
            "offer",
            "OSI",
            "offer selector",
            "OST",
            "price",
            "AOS",
            "product",
            "link offer",
            "arrangement code"
        ],
        "text": "Yes. To create an offer selector the assistant needs the product arrangement code, customer segment, market segment, and offer type; commitment, term, and price point are optional refinements. It asks for your confirmation, creates the selector in AOS, and returns the new OSI, which you or the assistant can then link to a card."
    },
    {
        "id": "offers-and-ost.md#6",
        "topic": "offers",
        "title": "Offers and the Offer Selector Tool (OST)",
        "section": "Is the Promotions page the same as a PROMOTION offer type?",
        "keywords": [
            "offer",
            "OSI",
            "offer selector",
            "OST",
            "price",
            "AOS",
            "product",
            "link offer",
            "arrangement code"
        ],
        "text": "No — they are different things that share a name. In the offer catalog, every offer has an offer type attribute such as BASE, TRIAL, or PROMOTION, describing what kind of purchasable offer it is. The Promotions page in MAS Studio manages promotion projects: named campaigns with a promo code, start and end dates, target geos and surfaces, and attached offers and cards, published on a schedule. When someone asks how promotions work in Studio, the answer is the Promotions page and its editor, not the offer type attribute."
    },
    {
        "id": "offers-and-ost.md#7",
        "topic": "offers",
        "title": "Offers and the Offer Selector Tool (OST)",
        "section": "What about offers that are not live yet (draft offers)?",
        "keywords": [
            "offer",
            "OSI",
            "offer selector",
            "OST",
            "price",
            "AOS",
            "product",
            "link offer",
            "arrangement code"
        ],
        "text": "OST searches published production offers by default. Offers that are still being onboarded exist in the DRAFT landscape and can be found by adding the commerce.landscape=DRAFT parameter to OST. A card authored against a draft offer switches automatically to the published version once the offer is released, so no re-authoring is needed. If you expect an offer to exist but cannot find it in either landscape, ask in the #merch-at-scale Slack channel."
    },
    {
        "id": "studio-basics.md#0",
        "topic": "studio",
        "title": "MAS Studio Basics",
        "section": "What is Merch at Scale (M@S)?",
        "keywords": [
            "MAS",
            "Merch at Scale",
            "Studio",
            "Odin",
            "AEM",
            "fragment",
            "surface",
            "locale",
            "adobe.com",
            "architecture",
            "features",
            "navigation",
            "side nav",
            "pages",
            "product catalog",
            "permissions",
            "admin"
        ],
        "text": "Merch at Scale is Adobe's platform for authoring, managing, and delivering merchandising content — merch cards with product information, live pricing, and purchase CTAs — across Adobe's digital properties. Instead of hardcoding product cards into each page, teams author a card once in MAS Studio and the same card can be delivered to adobe.com, Creative Cloud Desktop, Adobe Home, Adobe Express, and Unified Checkout. Prices are fetched from Adobe's commerce services when the card renders, so pricing stays current everywhere without re-authoring."
    },
    {
        "id": "studio-basics.md#1",
        "topic": "studio",
        "title": "MAS Studio Basics",
        "section": "What is MAS Studio?",
        "keywords": [
            "MAS",
            "Merch at Scale",
            "Studio",
            "Odin",
            "AEM",
            "fragment",
            "surface",
            "locale",
            "adobe.com",
            "architecture",
            "features",
            "navigation",
            "side nav",
            "pages",
            "product catalog",
            "permissions",
            "admin"
        ],
        "text": "MAS Studio is the web application at https://mas.adobe.com/studio.html where merch cards are created, edited, and published. It offers a visual editor with live preview, a folder tree organized by surface, table and rendered views of your cards, search and filtering, integration with the Offer Selector Tool for pricing, a publish workflow, and an AI assistant chat panel. You sign in with your Adobe corporate account through IMS, and what you can see and do is governed by IAM group permissions."
    },
    {
        "id": "studio-basics.md#2",
        "topic": "studio",
        "title": "MAS Studio Basics",
        "section": "Where does card content live?",
        "keywords": [
            "MAS",
            "Merch at Scale",
            "Studio",
            "Odin",
            "AEM",
            "fragment",
            "surface",
            "locale",
            "adobe.com",
            "architecture",
            "features",
            "navigation",
            "side nav",
            "pages",
            "product catalog",
            "permissions",
            "admin"
        ],
        "text": "Cards are stored as content fragments in Odin, Adobe's internal Adobe Experience Manager (AEM) instance for structured content. All MAS content lives under the /content/dam/mas/ path, organized into folders by surface and locale. A fragment is structured data — named fields such as title, description, prices, ctas, and variant — not a rendered page; rendering happens later in the merch-card web component on the consuming page. Always create and edit MAS fragments through MAS Studio rather than directly in the AEM authoring UI, so the card structure stays valid."
    },
    {
        "id": "studio-basics.md#3",
        "topic": "studio",
        "title": "MAS Studio Basics",
        "section": "How does a card reach adobe.com?",
        "keywords": [
            "MAS",
            "Merch at Scale",
            "Studio",
            "Odin",
            "AEM",
            "fragment",
            "surface",
            "locale",
            "adobe.com",
            "architecture",
            "features",
            "navigation",
            "side nav",
            "pages",
            "product catalog",
            "permissions",
            "admin"
        ],
        "text": "First, an author creates and publishes the card in MAS Studio, which publishes the content fragment in Odin. Second, an adobe.com page includes the merch-card web component referencing that fragment. Third, when the page loads, the component fetches the fragment as JSON from the MAS delivery endpoint at https://www.adobe.com/mas/io/fragment, which runs a processing pipeline including locale resolution, placeholder replacement, and pricing integration. Fourth, if the card has an Offer Selector ID, the current price is fetched from the Web Commerce Service (WCS) for the user's locale. Responses are cached at the Akamai edge for performance, so a just-published change can take a short while to appear."
    },
    {
        "id": "studio-basics.md#4",
        "topic": "studio",
        "title": "MAS Studio Basics",
        "section": "What are surfaces and locales in MAS?",
        "keywords": [
            "MAS",
            "Merch at Scale",
            "Studio",
            "Odin",
            "AEM",
            "fragment",
            "surface",
            "locale",
            "adobe.com",
            "architecture",
            "features",
            "navigation",
            "side nav",
            "pages",
            "product catalog",
            "permissions",
            "admin"
        ],
        "text": "Surfaces are the destinations where cards render: acom (adobe.com), ccd (Creative Cloud Desktop), adobe-home (Adobe Home), commerce (Unified Checkout), and express (Adobe Express), plus a sandbox area for testing. Locales use codes like en_US or fr_FR (language plus country), and content folders follow the pattern /content/dam/mas/ then surface then locale. A card has a locale-default parent fragment, and each locale can hold exactly one variation of it for translated or region-specific content. Prices localize automatically through the offer system, but card text does not — translated text requires locale variations, which can be produced through translation projects."
    },
    {
        "id": "studio-basics.md#5",
        "topic": "studio",
        "title": "MAS Studio Basics",
        "section": "What features does Merch at Scale Studio have?",
        "keywords": [
            "MAS",
            "Merch at Scale",
            "Studio",
            "Odin",
            "AEM",
            "fragment",
            "surface",
            "locale",
            "adobe.com",
            "architecture",
            "features",
            "navigation",
            "side nav",
            "pages",
            "product catalog",
            "permissions",
            "admin"
        ],
        "text": "MAS Studio covers the full merchandising content workflow. You can author and publish merch cards on the Fragments page, group cards into collections, create locale variations for regional content and grouped personalization variations, localize content with translation projects on the Translations page, manage placeholders — reusable text strings resolved into cards per surface and locale — on the Placeholders page, and manage promotions with promo codes, schedules, geos, and attached offers and cards on the Promotions page (admin-only). You can publish content at scale with bulk publish projects under Advanced tools, browse the product catalog and create cards for a product from its detail page, attach live pricing through the Offer Selector Tool, and use the AI assistant to search, publish, update, and create content conversationally. Global settings and masks are additional permission-gated tools under Advanced tools."
    },
    {
        "id": "studio-basics.md#6",
        "topic": "studio",
        "title": "MAS Studio Basics",
        "section": "What pages are in the Studio side navigation?",
        "keywords": [
            "MAS",
            "Merch at Scale",
            "Studio",
            "Odin",
            "AEM",
            "fragment",
            "surface",
            "locale",
            "adobe.com",
            "architecture",
            "features",
            "navigation",
            "side nav",
            "pages",
            "product catalog",
            "permissions",
            "admin"
        ],
        "text": "The side navigation contains Home (quick actions and recently updated cards), Product Catalog, Fragments (the card content table), Collections (currently disabled — collections are managed from the Fragments page), Promotions, Placeholders, Translations, AI Assistant, and Advanced tools. The Promotions page only appears for members of the MAS admins group. Advanced tools contains three tools: Bulk publish (available to everyone), Global settings (admins and surface power users; on the sandbox, commerce, and nala surfaces it is admin-only), and Masks (permission-gated, for authoring reusable card overlays applied at delivery time). If a page you expect is missing from your side navigation, you are most likely missing the corresponding group membership."
    },
    {
        "id": "studio-basics.md#7",
        "topic": "studio",
        "title": "MAS Studio Basics",
        "section": "How do I browse the product catalog?",
        "keywords": [
            "MAS",
            "Merch at Scale",
            "Studio",
            "Odin",
            "AEM",
            "fragment",
            "surface",
            "locale",
            "adobe.com",
            "architecture",
            "features",
            "navigation",
            "side nav",
            "pages",
            "product catalog",
            "permissions",
            "admin"
        ],
        "text": "The Product Catalog page lists Adobe products in a sortable table with columns for name, product code, arrangement code, product family, customer segment, markets, and plan types, plus facet filters for markets, plan types, customer segments, and product families and a text search. Clicking a product opens its detail page. From the product detail page you can create a card for that product: pick the surface, locale, and one or more card variants, and Studio opens the Offer Selector Tool pre-filtered to the product's arrangement code so you can pick the offer that prices the card."
    },
    {
        "id": "studio-basics.md#8",
        "topic": "studio",
        "title": "MAS Studio Basics",
        "section": "What can the AI assistant in Studio do?",
        "keywords": [
            "MAS",
            "Merch at Scale",
            "Studio",
            "Odin",
            "AEM",
            "fragment",
            "surface",
            "locale",
            "adobe.com",
            "architecture",
            "features",
            "navigation",
            "side nav",
            "pages",
            "product catalog",
            "permissions",
            "admin"
        ],
        "text": "The assistant can search cards by title, content, tags, surface, locale, or linked offer ID; fetch a card's contents; open a card in the editor; and copy a deep link to a card. It can publish, unpublish, update, and duplicate cards, run bulk updates and bulk publishes with dry-run previews, create and inspect locale variations, create collections and add cards to them, and create tags. On the commerce side it can search products and offers, resolve OSIs, create offer selectors, link offers to cards, and validate card-offer consistency. It also supports translation coverage reports, finding untranslated cards, translation projects, a guided flow for creating new product release cards, and opening the Offer Selector Tool. Every state-changing action asks for your explicit confirmation before it runs."
    },
    {
        "id": "studio-pages.md#0",
        "topic": "studio-pages",
        "title": "Studio pages and editors",
        "section": "What does the fragment editor do?",
        "keywords": [
            "fragment editor",
            "advanced tools",
            "masks",
            "mask",
            "global settings",
            "locale picker",
            "region picker",
            "rollout",
            "roll out",
            "rollout project",
            "preview",
            "preview on page",
            "render view",
            "table view",
            "permission",
            "gated",
            "access",
            "side rail",
            "breadcrumb"
        ],
        "text": "The fragment editor is the full-page editor for one card, collection or compare chart, with a live preview of the card beside the form. It opens from the Fragments list and shows the fields for the card's template, a side rail, and an action toolbar. From it you can save, publish, duplicate, delete, and set a variation type, and its dialogs include Confirm Deletion (which warns when the card has locale variations), Confirm Discard, and Confirm Cloning, which asks for a new title, an OSI search and tags. The side rail includes the Copy Field button, which produces a link for using a single field of the card on a page. Breadcrumbs show where you are, for example Fragments then Editor."
    },
    {
        "id": "studio-pages.md#1",
        "topic": "studio-pages",
        "title": "Studio pages and editors",
        "section": "What is the Advanced tools page?",
        "keywords": [
            "fragment editor",
            "advanced tools",
            "masks",
            "mask",
            "global settings",
            "locale picker",
            "region picker",
            "rollout",
            "roll out",
            "rollout project",
            "preview",
            "preview on page",
            "render view",
            "table view",
            "permission",
            "gated",
            "access",
            "side rail",
            "breadcrumb"
        ],
        "text": "Advanced tools is a hub page whose cards link to Bulk publish, Global settings and Masks. It is the entry point for the operations that are not part of everyday card authoring. The Global settings and Masks cards are permission gated, so which cards you see depends on your access for the current surface."
    },
    {
        "id": "studio-pages.md#2",
        "topic": "studio-pages",
        "title": "Studio pages and editors",
        "section": "What are masks in MAS Studio?",
        "keywords": [
            "fragment editor",
            "advanced tools",
            "masks",
            "mask",
            "global settings",
            "locale picker",
            "region picker",
            "rollout",
            "roll out",
            "rollout project",
            "preview",
            "preview on page",
            "render view",
            "table view",
            "permission",
            "gated",
            "access",
            "side rail",
            "breadcrumb"
        ],
        "text": "A mask is a reusable card overlay applied at delivery time, rather than something baked into each card. The Masks list has a region picker and a Create mask action, with columns for Name, Description, Last updated by, Last published by and Status, and a row menu offering Edit, Publish and Delete. The mask editor has a Title, Name, Description, a template picker and a Placeholders multifield where you add variables. Masks are reached from Advanced tools."
    },
    {
        "id": "studio-pages.md#3",
        "topic": "studio-pages",
        "title": "Studio pages and editors",
        "section": "Who can see Masks and Global settings?",
        "keywords": [
            "fragment editor",
            "advanced tools",
            "masks",
            "mask",
            "global settings",
            "locale picker",
            "region picker",
            "rollout",
            "roll out",
            "rollout project",
            "preview",
            "preview on page",
            "render view",
            "table view",
            "permission",
            "gated",
            "access",
            "side rail",
            "breadcrumb"
        ],
        "text": "Both are gated behind the same permission check. Access requires membership of the MAS admins group or of the current surface's power-user group, so access is per surface: a user may see settings on one surface and not another. The commerce, sandbox and nala surfaces are admin only. If you are not permitted, the Masks page says you do not have access to masks for this surface, and navigating directly to the settings page redirects you to Home rather than showing an error."
    },
    {
        "id": "studio-pages.md#4",
        "topic": "studio-pages",
        "title": "Studio pages and editors",
        "section": "What is the locale picker for?",
        "keywords": [
            "fragment editor",
            "advanced tools",
            "masks",
            "mask",
            "global settings",
            "locale picker",
            "region picker",
            "rollout",
            "roll out",
            "rollout project",
            "preview",
            "preview on page",
            "render view",
            "table view",
            "permission",
            "gated",
            "access",
            "side rail",
            "breadcrumb"
        ],
        "text": "The locale picker, also called the region picker, selects which locale you are working in. Studio scopes what you see to the currently selected surface and locale, so the Fragments list, the Placeholders page and the Masks list all follow it. It also appears inside dialogs, notably when setting a variation type, where a regional locale picker chooses the target locale for a new locale variation. It is enabled in more editor states than it once was, including on grouped variations, and language switching also works for promo variations."
    },
    {
        "id": "studio-pages.md#5",
        "topic": "studio-pages",
        "title": "Studio pages and editors",
        "section": "How do I roll out a card to other locales (rollout project)?",
        "keywords": [
            "fragment editor",
            "advanced tools",
            "masks",
            "mask",
            "global settings",
            "locale picker",
            "region picker",
            "rollout",
            "roll out",
            "rollout project",
            "preview",
            "preview on page",
            "render view",
            "table view",
            "permission",
            "gated",
            "access",
            "side rail",
            "breadcrumb"
        ],
        "text": "To roll out a card to other locales without translating it, use a rollout project. A rollout project is a translation project whose type is set to Rollout instead of Translation. Rather than sending content out for translation, it copies the selected content into the target locales as-is. Use it when you need locale copies of a card without changing the text, for example when the content is language neutral or will be edited by hand per locale. You choose Translation or Rollout with the Project Type control when creating the project in the translation project editor, and both kinds go through the same submission pipeline and show the same statuses on the Translations page."
    },
    {
        "id": "studio-pages.md#6",
        "topic": "studio-pages",
        "title": "Studio pages and editors",
        "section": "What is the difference between Render view and Table view?",
        "keywords": [
            "fragment editor",
            "advanced tools",
            "masks",
            "mask",
            "global settings",
            "locale picker",
            "region picker",
            "rollout",
            "roll out",
            "rollout project",
            "preview",
            "preview on page",
            "render view",
            "table view",
            "permission",
            "gated",
            "access",
            "side rail",
            "breadcrumb"
        ],
        "text": "The Fragments list can show content either as rendered cards or as a table. The toolbar carries the Filter button with a count badge, a Search box, a Create menu offering Merch Card, Merch Card Collection and Compare chart, a Select action for multi-select mode, and the Render view / Table view switch. Render view is for recognising cards visually; Table view is for scanning many rows and for multi-select work."
    },
    {
        "id": "studio-pages.md#7",
        "topic": "studio-pages",
        "title": "Studio pages and editors",
        "section": "How do I preview a card on a real page?",
        "keywords": [
            "fragment editor",
            "advanced tools",
            "masks",
            "mask",
            "global settings",
            "locale picker",
            "region picker",
            "rollout",
            "roll out",
            "rollout project",
            "preview",
            "preview on page",
            "render view",
            "table view",
            "permission",
            "gated",
            "access",
            "side rail",
            "breadcrumb"
        ],
        "text": "Use the Preview action, available from the fragment editor's action bar and from a row in the Fragments table. It opens the card on a Milo preview page in a new tab, passing the fragment id, whether it is a card or a collection, and the locale taken from the fragment's path. Which host it opens depends on the card's status: a published card previews on the production Milo host, and an unpublished one previews on the Milo branch host so you can see draft content. This is different from the live preview beside the form in the fragment editor, which shows the card on its own rather than on a page."
    },
    {
        "id": "translations.md#0",
        "topic": "translations",
        "title": "Translations in MAS Studio",
        "section": "How do I create a translation project?",
        "keywords": [
            "translation",
            "translate",
            "localize",
            "localization",
            "locale",
            "language",
            "translation project",
            "rollout"
        ],
        "text": "Open the Translations page from the MAS Studio side navigation and click the \"Create project\" button. This opens the translation project editor, where you give the project a title, choose one or more target locales, and add the content to translate: cards (fragments), placeholders, and collections. A project cannot be saved until it has a title, at least one target locale, and at least one selected item. The title is used as the localization task name, so it must be at most 255 characters, contain at least one letter or number, and use only letters, numbers, hyphens, underscores, and dots (consecutive dots are not allowed). Translation projects are created on this page; the AI assistant cannot create or submit them."
    },
    {
        "id": "translations.md#1",
        "topic": "translations",
        "title": "Translations in MAS Studio",
        "section": "What does a translation project contain?",
        "keywords": [
            "translation",
            "translate",
            "localize",
            "localization",
            "locale",
            "language",
            "translation project",
            "rollout"
        ],
        "text": "A translation project is stored as a content fragment with these fields: title, status, fragments (the card paths to translate), placeholders, collections, targetLocales, submissionDate, and projectType. Target locales use the underscore format such as fr_FR, de_DE, or ja_JP. The projectType is \"translation\" by default; a second type, \"rollout\", exists for rollout-only projects that copy content to target locales without sending it for translation. The Translations page lists all projects in a table showing title, status, who last modified the project, and the \"Sent on\" date (the submission date, sortable). From the row action menu you can edit or delete a project; deleting is permanent. Duplicate and Archive also appear in the menu but are currently disabled."
    },
    {
        "id": "translations.md#2",
        "topic": "translations",
        "title": "Translations in MAS Studio",
        "section": "How do I add content and locales to a translation project?",
        "keywords": [
            "translation",
            "translate",
            "localize",
            "localization",
            "locale",
            "language",
            "translation project",
            "rollout"
        ],
        "text": "In the translation project editor, \"Add items\" opens an overlay with tabs for cards, placeholders, and collections; search and filters (template, market segment, customer segment, product) help find the content, and Cancel reverts to the selection you had when the overlay opened. \"Add languages\" opens the target-locale picker the same way. The editor's quick-action bar offers Save, the send-for-localization action, Copy, Discard, and Delete. You can also start a pre-filled project from the fragment editor: the missing-variation panel routes to a new translation project with that card and the missing locale already selected. Studio has no dedicated translation coverage page — the fragment editor's variations panel shows which locales a card has. The AI assistant cannot produce coverage reports; ask it to list a card's variation locales instead."
    },
    {
        "id": "translations.md#3",
        "topic": "translations",
        "title": "Translations in MAS Studio",
        "section": "How do I send a translation project for localization?",
        "keywords": [
            "translation",
            "translate",
            "localize",
            "localization",
            "locale",
            "language",
            "translation project",
            "rollout"
        ],
        "text": "After creating and saving the project, use the send-for-localization action in the translation project editor. Studio calls the translation-project-start backend action with the project ID and the current surface, authenticated with your IMS token. On success the submission date is stamped on the project, its status becomes Pending, and the project becomes read-only in the editor. This is a Studio action only; the AI assistant cannot submit a project for you."
    },
    {
        "id": "translations.md#4",
        "topic": "translations",
        "title": "Translations in MAS Studio",
        "section": "What do the translation project statuses mean?",
        "keywords": [
            "translation",
            "translate",
            "localize",
            "localization",
            "locale",
            "language",
            "translation project",
            "rollout"
        ],
        "text": "The status column on the Translations page maps internal states to labels. \"Pending\" (internal status QUEUED) means the submission was accepted and the job is waiting in the queue. \"Running\" (RUNNING) means the job is being processed, including content synchronization. \"Sent to loc\" (ASYNC_PROCESSING) means the content has been handed off to the localization service and is out for translation. \"Failed\" (FAILED) means the job did not complete; the project can be inspected and resubmitted. These statuses are visible on the Translations page; the assistant cannot query them."
    },
    {
        "id": "translations.md#5",
        "topic": "translations",
        "title": "Translations in MAS Studio",
        "section": "What happens after I submit a translation project?",
        "keywords": [
            "translation",
            "translate",
            "localize",
            "localization",
            "locale",
            "language",
            "translation project",
            "rollout"
        ],
        "text": "Submission is asynchronous. The translation-project-start action validates the request, marks the project QUEUED with a submission date, stores the job payload, enqueues the job, and invokes a dispatcher action in the background, returning immediately. The worker then runs a sync stage before localization: placeholder entries are added to the dictionary index of each target locale, and for grouped (pzn) variations the parent fragments in each target locale are updated to reference the translated variations so they stay linked. After syncing, the worker sends the localization request to the AEM/Odin localization endpoint with the task name, the content fragment paths, and the target locales. The translation flow is determined per surface (for example transcreation) unless human translation is configured."
    },
    {
        "id": "translations.md#6",
        "topic": "translations",
        "title": "Translations in MAS Studio",
        "section": "What is a rollout project?",
        "keywords": [
            "translation",
            "translate",
            "localize",
            "localization",
            "locale",
            "language",
            "translation project",
            "rollout"
        ],
        "text": "A rollout project is a translation project whose projectType field is set to \"rollout\". Instead of sending content out for translation, the backend sends the selected content paths and target locales to the Odin locale-sync endpoint, which copies the content into the target locales as-is. This is useful when you need locale copies of fragments without changing the text, for example when the content is language-neutral or will be edited manually per locale. Rollout projects go through the same submission pipeline as translation projects: they are queued, synced, and dispatched asynchronously, and the same status labels apply on the Translations page."
    },
    {
        "id": "translations.md#7",
        "topic": "translations",
        "title": "Translations in MAS Studio",
        "section": "What can the AI assistant do with translations?",
        "keywords": [
            "translation",
            "translate",
            "localize",
            "localization",
            "locale",
            "language",
            "translation project",
            "rollout"
        ],
        "text": "Nothing directly. Translation projects are created, edited and submitted on the Translations page in Studio, not through the assistant.\n\nWhat the assistant can help with is the variation side of localization: it can show a card's variation tree, list which locales a card already has variations for, find the parent of a variation, and create a new locale variation of a card. So \"which locales does this card have?\" is answerable, while \"create a translation project for these\" is not."
    },
    {
        "id": "translations.md#8",
        "topic": "translations",
        "title": "Translations in MAS Studio",
        "section": "Are prices and offers translated too?",
        "keywords": [
            "translation",
            "translate",
            "localize",
            "localization",
            "locale",
            "language",
            "translation project",
            "rollout"
        ],
        "text": "No, and they do not need to be. Card prices come from the offer selector (OSI), which adapts automatically to the page locale: currency, tax labels, and checkout links are resolved at render time by the commerce backend. The same OSI works across locales as long as the offer is valid there. Commerce placeholders are likewise resolved by backend locale logic rather than translated. What translation projects handle is the authored card content itself — titles, descriptions, and other text fields — which is not auto-translated and must go through a translation project (or be authored separately per locale)."
    },
    {
        "id": "troubleshooting.md#0",
        "topic": "troubleshooting",
        "title": "Troubleshooting MAS Studio",
        "section": "Why is my card not showing on the page (fragment not found)?",
        "keywords": [
            "error",
            "fragment not found",
            "publish failed",
            "price not showing",
            "404",
            "401",
            "403",
            "help",
            "slack"
        ],
        "text": "A \"fragment not found\" or 404 error means the delivery API cannot find the fragment at the requested path. Check three things. First, the card must be Published, not Draft or Modified — unpublished fragments are not delivered. Second, the fragment path must be exact and is case-sensitive; it starts with /content/dam/mas/. Third, test delivery directly by opening https://www.adobe.com/mas/io/fragment with the path parameter set to your fragment path — a working fragment returns JSON. If the card was just published, edge caching can briefly serve stale results; hard refresh and retry after a minute or two. You can also ask the AI assistant to search for the card to confirm it exists and check its status."
    },
    {
        "id": "troubleshooting.md#1",
        "topic": "troubleshooting",
        "title": "Troubleshooting MAS Studio",
        "section": "Why is the price not showing on my card?",
        "keywords": [
            "error",
            "fragment not found",
            "publish failed",
            "price not showing",
            "404",
            "401",
            "403",
            "help",
            "slack"
        ],
        "text": "Prices are fetched at render time from the Web Commerce Service (WCS) using the card's Offer Selector ID (OSI). Verify the OSI field has a value and that the card was saved after inserting it — the OSI only persists after a save. Then verify the offer is valid for the page's locale and country and that today falls within its availability dates; a WCS response of 200 with an empty body usually means the offer is not available for that locale. In the browser network tab, look for requests containing web_commerce_artifact and inspect the response. The AI assistant can resolve the OSI to its offer details so you can confirm the offer exists, and it can validate that the card and its linked offer are consistent."
    },
    {
        "id": "troubleshooting.md#2",
        "topic": "troubleshooting",
        "title": "Troubleshooting MAS Studio",
        "section": "Why can't I publish my card?",
        "keywords": [
            "error",
            "fragment not found",
            "publish failed",
            "price not showing",
            "404",
            "401",
            "403",
            "help",
            "slack"
        ],
        "text": "The most common causes are missing permissions, validation errors, or a temporary backend issue. Publishing requires a publisher role through your IAM group membership — being able to edit does not imply being able to publish. Validation errors also block publishing: check for red error indicators and fill all required fields for the card's variant. If permissions and validation are fine, it may be a temporary issue in the AEM backend; retry later, and if it persists ask in the #merch-at-scale Slack channel. For publishing many cards, the AI assistant can show a preview of exactly which cards a bulk publish would affect before running it."
    },
    {
        "id": "troubleshooting.md#3",
        "topic": "troubleshooting",
        "title": "Troubleshooting MAS Studio",
        "section": "Why don't I see Promotions or Global settings in the side navigation?",
        "keywords": [
            "error",
            "fragment not found",
            "publish failed",
            "price not showing",
            "404",
            "401",
            "403",
            "help",
            "slack"
        ],
        "text": "Those pages are group-gated, not broken. Promotions is only rendered for members of the MAS admins group. Global settings requires admin membership or the surface's power-users group, and on the sandbox, commerce, and nala surfaces it is admin-only; Masks is gated the same way. Collections appears in the navigation but is currently disabled for everyone. If you need one of these pages, request the matching group through IAM, then sign out of Studio and back in so the new membership is picked up."
    },
    {
        "id": "troubleshooting.md#4",
        "topic": "troubleshooting",
        "title": "Troubleshooting MAS Studio",
        "section": "What do 401 and 403 errors mean?",
        "keywords": [
            "error",
            "fragment not found",
            "publish failed",
            "price not showing",
            "404",
            "401",
            "403",
            "help",
            "slack"
        ],
        "text": "A 401 means your IMS session token is expired or invalid: sign out of Studio and sign back in; clearing the browser's session storage for the site also helps. A 403 means you are authenticated but lack permission for the action: check your IAM group membership. If you can log in but see no content at all, you are likely missing the surface-specific author group for the surface you are browsing. Request the needed groups through Adobe's IAM system, allow time for provisioning, then log out and back in."
    },
    {
        "id": "troubleshooting.md#5",
        "topic": "troubleshooting",
        "title": "Troubleshooting MAS Studio",
        "section": "Why does OST show no results for my search?",
        "keywords": [
            "error",
            "fragment not found",
            "publish failed",
            "price not showing",
            "404",
            "401",
            "403",
            "help",
            "slack"
        ],
        "text": "Several causes are common. The offer may not be valid for the locale you are authoring in — offers are onboarded per country. Its availability dates may exclude today. It may still be a draft offer, which only appears when searching the DRAFT landscape (add the commerce.landscape=DRAFT parameter). Or it may not exist yet. The AI assistant can search the offer catalog with filters and list matching products, which quickly confirms whether the offer exists at all before you dig further."
    },
    {
        "id": "troubleshooting.md#6",
        "topic": "troubleshooting",
        "title": "Troubleshooting MAS Studio",
        "section": "The AI assistant gave an error or a wrong result — what should I do?",
        "keywords": [
            "error",
            "fragment not found",
            "publish failed",
            "price not showing",
            "404",
            "401",
            "403",
            "help",
            "slack"
        ],
        "text": "Retry the request once — transient backend errors happen. If the conversation seems stuck in the middle of a flow, ask to start over; this clears the chat and any in-progress flow state. Note that the assistant always asks for confirmation before publishing, updating, or creating anything, so an error never means something was changed without your approval. If a problem persists, report it in the #merch-at-scale Slack channel with what you asked and roughly when."
    },
    {
        "id": "troubleshooting.md#7",
        "topic": "troubleshooting",
        "title": "Troubleshooting MAS Studio",
        "section": "Where do I get help?",
        "keywords": [
            "error",
            "fragment not found",
            "publish failed",
            "price not showing",
            "404",
            "401",
            "403",
            "help",
            "slack"
        ],
        "text": "The #merch-at-scale Slack channel is the main channel for all MAS questions: authoring help, Studio bugs, publishing problems, and access requests. The team has a no-direct-message policy, so post in the channel rather than messaging individuals — answers in channel help everyone. For pricing and offer catalog data issues use #catalog-support, and for adobe.com page integration questions use #milo-dev. Bugs are tracked in the Jira MWPW project; a good report includes steps to reproduce, the fragment path, the OSI if pricing-related, the environment, and screenshots."
    },
    {
        "id": "troubleshooting.md#8",
        "topic": "troubleshooting",
        "title": "Troubleshooting MAS Studio",
        "section": "Why is my card showing English text on a non-English page?",
        "keywords": [
            "error",
            "fragment not found",
            "publish failed",
            "price not showing",
            "404",
            "401",
            "403",
            "help",
            "slack"
        ],
        "text": "The card is falling back to English because the localized content is not being found for that locale. Check three things in order. First, does the card actually have a variation for that locale? A card with no locale variation renders its parent, which is usually the English one. Second, are the placeholders resolved? Placeholder text is looked up in the dictionary for that surface and locale, and a key missing there falls back up the chain, so a card can be localized while its placeholder labels are not. Third, is the page requesting the locale you think it is? The locale comes from the page's own path and country handling, so an English-looking page URL will fetch English content even when a localized variation exists. Prices and checkout links are a separate matter: they are resolved by the commerce backend from the offer and adapt to the market automatically, so they are not translated and do not need a variation."
    }
];
