/**
 * GENERATED FILE — do not edit by hand.
 * Source: src/ai-chat/knowledge/*.md — regenerate with `npm run build:knowledge`.
 * The corpus sync test fails when this file is out of date.
 */

export const KNOWLEDGE_CHUNKS = [
    {
        id: 'bulk-operations.md#0',
        topic: 'bulk-operations',
        title: 'Bulk Operations in MAS Studio',
        section: 'How do I update many cards at once with the AI assistant?',
        keywords: [
            'bulk',
            'bulk update',
            'bulk publish',
            'bulk unpublish',
            'publish multiple',
            'batch',
            'mass update',
            'find and replace',
            'preview',
        ],
        text: 'Search first, then ask for the change. For example: "find cards with \'20+ apps\'", then "change 20+ apps to 30+ apps". The assistant applies the change to the cards from your last search using the bulk_update_cards operation. A bulk update can carry common field updates applied to every card, text find-and-replace operations, or both. The assistant always generates a preview first and waits for your approval before anything is modified. Outside of chat, Studio\'s table view also supports bulk actions: select cards with the checkboxes and use the bulk actions menu.',
    },
    {
        id: 'bulk-operations.md#1',
        topic: 'bulk-operations',
        title: 'Bulk Operations in MAS Studio',
        section: 'How does the preview and approval workflow for bulk operations work?',
        keywords: [
            'bulk',
            'bulk update',
            'bulk publish',
            'bulk unpublish',
            'publish multiple',
            'batch',
            'mass update',
            'find and replace',
            'preview',
        ],
        text: 'Every bulk update and bulk publish is a mandatory two-step process. First the assistant runs a read-only preview (preview_bulk_update or preview_bulk_publish) and shows you exactly which cards would be affected and what would change. Nothing is modified at this stage. Only after you approve — saying "yes", "approve", or "proceed" — does the assistant execute the real operation (bulk_update_cards or bulk_publish_cards) with the same parameters as the preview. If you say "no" or "cancel", the operation is cancelled and the cards are left untouched. Execution is additionally guarded by an explicit confirmation, such as "Apply update to N cards?" or "Publish N cards to production?", because bulk operations are state-changing.',
    },
    {
        id: 'bulk-operations.md#2',
        topic: 'bulk-operations',
        title: 'Bulk Operations in MAS Studio',
        section: 'Where do the card IDs for a bulk operation come from?',
        keywords: [
            'bulk',
            'bulk update',
            'bulk publish',
            'bulk unpublish',
            'publish multiple',
            'batch',
            'mass update',
            'find and replace',
            'preview',
        ],
        text: 'Bulk operations act on fragment IDs from your conversation context: either the results of a previous search or operation (the last operation\'s fragment IDs) or the working set of cards shown after a tool result. Fragment IDs are AEM UUIDs and cannot be derived from card titles, so the assistant will never invent or guess them. If you ask for a bulk change before searching, the assistant asks you to find the cards first, for example "find cards titled X in sandbox", and then apply the change. When it does run a bulk operation, the complete ID list from the search is used — the set is never truncated or sampled, so if your search returned 26 cards, all 26 are included.',
    },
    {
        id: 'bulk-operations.md#3',
        topic: 'bulk-operations',
        title: 'Bulk Operations in MAS Studio',
        section: 'How do find-and-replace text updates work in bulk updates?',
        keywords: [
            'bulk',
            'bulk update',
            'bulk publish',
            'bulk unpublish',
            'publish multiple',
            'batch',
            'mass update',
            'find and replace',
            'preview',
        ],
        text: 'Each text replacement specifies the text to find, the text to replace it with, and optionally a field name. If a field is given (for example title), only that field is searched and updated on each card. If the field is omitted, every field of each card is searched automatically and the text is replaced wherever it appears. Matching is against the literal string you provide. Several replacements can be combined in one bulk update, and replacements can be mixed with common field updates that set the same value on all selected cards. The preview step shows the resulting changes per card before you approve.',
    },
    {
        id: 'bulk-operations.md#4',
        topic: 'bulk-operations',
        title: 'Bulk Operations in MAS Studio',
        section: 'How do I bulk publish or unpublish cards?',
        keywords: [
            'bulk',
            'bulk update',
            'bulk publish',
            'bulk unpublish',
            'publish multiple',
            'batch',
            'mass update',
            'find and replace',
            'preview',
        ],
        text: 'After a search, ask the assistant to "publish these cards", "publish all", or "unpublish those cards". The bulk_publish_cards operation takes the card IDs from your search context plus an action of publish or unpublish. As with updates, the assistant first shows a preview via preview_bulk_publish listing the cards that would be published or unpublished, and executes only after you approve, with a final confirmation like "Publish N cards to production?". In Studio itself you can also select cards in the table view with checkboxes and choose "Publish selected" from the bulk actions menu.',
    },
    {
        id: 'bulk-operations.md#5',
        topic: 'bulk-operations',
        title: 'Bulk Operations in MAS Studio',
        section: 'Can I bulk delete cards?',
        keywords: [
            'bulk',
            'bulk update',
            'bulk publish',
            'bulk unpublish',
            'publish multiple',
            'batch',
            'mass update',
            'find and replace',
            'preview',
        ],
        text: 'No. Bulk deletion is not supported by the AI assistant, and it will not emit a bulk delete operation under any circumstances. If you ask to delete multiple cards, the assistant declines and directs you to MAS Studio, where fragments can be deleted individually through the UI with a confirmation dialog. Single-card deletion is likewise not performed by the assistant. This is a deliberate safety restriction, since deletion is destructive and cannot be previewed and approved the way bulk updates and publishes can.',
    },
    {
        id: 'bulk-operations.md#6',
        topic: 'bulk-operations',
        title: 'Bulk Operations in MAS Studio',
        section: 'What is the Bulk Publishing page in Studio?',
        keywords: [
            'bulk',
            'bulk update',
            'bulk publish',
            'bulk unpublish',
            'publish multiple',
            'batch',
            'mass update',
            'find and replace',
            'preview',
        ],
        text: 'Separate from the chat-based bulk tools, Studio has a bulk publishing feature built around bulk publish projects: a saved project holds a list of fragment paths and target locales. Publishing a project dispatches an asynchronous backend worker (the request is accepted immediately and runs in the background) that resolves every path in every selected locale, takes a snapshot of the current published state, and then publishes the resolved fragments. The project ends in one of three statuses: Published, Partially published, or Failed. Fragments that do not exist in a target locale are reported as not localized rather than failing silently. Because a snapshot is taken before publishing, a bulk publish can be reverted, and Studio checks whether entries were modified after the snapshot before allowing a revert.',
    },
    {
        id: 'bulk-operations.md#7',
        topic: 'bulk-operations',
        title: 'Bulk Operations in MAS Studio',
        section: 'How do I see the cards from my last bulk operation?',
        keywords: [
            'bulk',
            'bulk update',
            'bulk publish',
            'bulk unpublish',
            'publish multiple',
            'batch',
            'mass update',
            'find and replace',
            'preview',
        ],
        text: 'Ask the assistant "show me the cards we updated", "list the cards from our last search", or "show me those cards again". The list_context_cards operation renders the cards referenced by the previous operation, using the fragment IDs stored in the conversation context, and works after searches, updates, and publishes alike. If there is no previous operation in the conversation, the assistant tells you that no prior card set exists instead of guessing. This is useful for verifying the outcome of a bulk update or publish without running a new search.',
    },
    {
        id: 'cards-and-publishing.md#0',
        topic: 'cards',
        title: 'Cards and Publishing in MAS Studio',
        section: 'How do I create a card in MAS Studio?',
        keywords: [
            'card',
            'merch card',
            'variant',
            'create card',
            'publish',
            'unpublish',
            'edit fields',
            'draft',
            'modified',
            'surface',
        ],
        text: 'Open MAS Studio at https://mas.adobe.com/studio.html, navigate the folder tree to the surface and folder where the card should live, and click Create. Pick the card variant that fits your surface and use case, then fill in the fields in the editor panel: title, description, prices, CTAs, and optional extras such as a badge, mnemonics (product icons), or a background image. The editor shows a live preview as you type. Saving stores the card as a content fragment in Draft status; it is not visible to end users until you publish it. You can also describe the card you want to the AI assistant in the chat panel, or duplicate an existing card and edit the copy — the assistant can duplicate a card for you if you give it the card ID.',
    },
    {
        id: 'cards-and-publishing.md#1',
        topic: 'cards',
        title: 'Cards and Publishing in MAS Studio',
        section: 'Which card variants exist and which surfaces use them?',
        keywords: [
            'card',
            'merch card',
            'variant',
            'create card',
            'publish',
            'unpublish',
            'edit fields',
            'draft',
            'modified',
            'surface',
        ],
        text: 'Each surface supports a specific set of card variants. Adobe.com (acom) uses plans, plans-students, plans-education, catalog, special-offers, mini, and simplified-pricing-express. Creative Cloud Desktop (ccd) uses ccd-slice and ccd-suggested. The commerce surface (Unified Checkout) uses fries, a horizontal commerce-focused card. Adobe Home uses ah-try-buy-widget and ah-promoted-plans. Adobe Express uses full-pricing-express and simplified-pricing-express. Variants differ in layout, required fields, and CTA styling: plans cards require a title, prices, and CTAs and use primary-outline CTAs, while fries cards require a title, description, and CTAs and use primary CTAs. Choose the variant first, because it determines which fields the editor offers.',
    },
    {
        id: 'cards-and-publishing.md#2',
        topic: 'cards',
        title: 'Cards and Publishing in MAS Studio',
        section: 'What is a surface and how does it affect my card?',
        keywords: [
            'card',
            'merch card',
            'variant',
            'create card',
            'publish',
            'unpublish',
            'edit fields',
            'draft',
            'modified',
            'surface',
        ],
        text: 'A surface is a destination where merch cards render: acom (adobe.com pages), ccd (Creative Cloud Desktop), commerce (Unified Checkout), adobe-home (Adobe Home), and express (Adobe Express). There is also a sandbox area for testing. Card content is stored under the /content/dam/mas/ path in AEM, organized into folders per surface, so the folder where you create a card determines its surface, and the surface determines which variants are valid. The AI assistant detects the surface from the folder you are currently browsing and suggests matching variants, and card searches can be filtered by surface and locale.',
    },
    {
        id: 'cards-and-publishing.md#3',
        topic: 'cards',
        title: 'Cards and Publishing in MAS Studio',
        section: 'How do I publish a card?',
        keywords: [
            'card',
            'merch card',
            'variant',
            'create card',
            'publish',
            'unpublish',
            'edit fields',
            'draft',
            'modified',
            'surface',
        ],
        text: 'Open the card in the editor, make sure there are no validation errors and all required fields for the variant are filled, then use the Publish action and confirm. The card status changes from Draft to Published and the fragment becomes available to consuming pages through the delivery API. You can also select multiple cards in the table view and publish them together. The AI assistant can publish a card if you ask (for example "publish this card"); it always asks for your confirmation before publishing, and for multiple cards it can first show a preview of exactly which cards would be affected before running the job.',
    },
    {
        id: 'cards-and-publishing.md#4',
        topic: 'cards',
        title: 'Cards and Publishing in MAS Studio',
        section: 'What happens when I edit a card that is already published?',
        keywords: [
            'card',
            'merch card',
            'variant',
            'create card',
            'publish',
            'unpublish',
            'edit fields',
            'draft',
            'modified',
            'surface',
        ],
        text: 'Cards have three statuses in Studio: Draft, Published, and Modified. When you edit and save a card that was already published, its status becomes Modified, meaning it has unpublished changes. Publish the card again so the live version picks up your edits. The status indicator in the content table shows where each card stands: Draft (never published), Published (live and unchanged), or Modified (live but with pending changes).',
    },
    {
        id: 'cards-and-publishing.md#5',
        topic: 'cards',
        title: 'Cards and Publishing in MAS Studio',
        section: 'How do I unpublish a card and what happens to pages using it?',
        keywords: [
            'card',
            'merch card',
            'variant',
            'create card',
            'publish',
            'unpublish',
            'edit fields',
            'draft',
            'modified',
            'surface',
        ],
        text: 'Unpublishing removes a card from delivery, so any live page that references the fragment stops rendering it. Typical reasons to unpublish are an ended promotion, outdated content, or deprecating a card. Open the card and use the Unpublish action, or select several cards and unpublish in bulk. The AI assistant can unpublish a single card or a batch of cards by ID; because this changes production it always asks you to confirm first. After unpublishing, remember to update any pages that referenced the card.',
    },
    {
        id: 'cards-and-publishing.md#6',
        topic: 'cards',
        title: 'Cards and Publishing in MAS Studio',
        section: 'Can the AI assistant edit cards for me?',
        keywords: [
            'card',
            'merch card',
            'variant',
            'create card',
            'publish',
            'unpublish',
            'edit fields',
            'draft',
            'modified',
            'surface',
        ],
        text: "Yes. The assistant can update fields on a single card, run a bulk update across many cards (including text replacements), duplicate a card, open a card in the Studio editor for you, and copy a deep link to a card. Before any bulk update it can show a dry-run preview of exactly what would change on each card, and every change requires your explicit confirmation before it runs. It can also search cards by title, content, tags, surface, locale, or linked offer ID, and fetch a card's full contents when you just want to read it.",
    },
    {
        id: 'cards-and-publishing.md#7',
        topic: 'cards',
        title: 'Cards and Publishing in MAS Studio',
        section: 'How do locale variations of a card work?',
        keywords: [
            'card',
            'merch card',
            'variant',
            'create card',
            'publish',
            'unpublish',
            'edit fields',
            'draft',
            'modified',
            'surface',
        ],
        text: "A card has a locale-default parent fragment, and each locale can have exactly one variation of it — attempting to create a second variation for the same locale fails. Variations carry translated or region-specific content while staying linked to the parent. The AI assistant can show a card's full variation tree, list which locales already have variations, find the parent of a variation, and create a new locale variation of a card (with confirmation). To find gaps, ask it to list cards that are missing a variation for a target locale.",
    },
    {
        id: 'collections-and-variations.md#0',
        topic: 'collections-and-variations',
        title: 'Collections and Variations in MAS Studio',
        section: 'What is a card collection?',
        keywords: [
            'collection',
            'merch card collection',
            'variation',
            'locale variation',
            'grouped variation',
            'pzn',
            'personalization',
            'locale default',
            'parent fragment',
            'translation',
        ],
        text: 'A collection is an AEM content fragment that groups merch cards. It uses the dedicated collection fragment model and is tagged mas:studio/content-type/merch-card-collection. The collection stores references to its member cards in a multi-value field along with a display label. Collections live in the same surface and locale folder structure as cards, and they can be attached to promotions alongside individual cards. Grouped (personalization) variations can also be created for collections, not only for cards.',
    },
    {
        id: 'collections-and-variations.md#1',
        topic: 'collections-and-variations',
        title: 'Collections and Variations in MAS Studio',
        section: 'How do I create a collection with the AI assistant?',
        keywords: [
            'collection',
            'merch card collection',
            'variation',
            'locale variation',
            'grouped variation',
            'pzn',
            'personalization',
            'locale default',
            'parent fragment',
            'translation',
        ],
        text: 'The assistant supports a create_collection action. It needs a title and a parent path (the folder the collection is created in), and optionally tags; because it is a state-changing operation, the assistant asks for confirmation before executing it. In the chat UI, when cards have been found or selected, the assistant can show a collection preview that renders each card, lets you edit the collection title (with an AI-suggested title prefilled when available), and creates the collection with those cards once you confirm. Collections created from chat land in the currently selected folder and locale, defaulting to en_US.',
    },
    {
        id: 'collections-and-variations.md#2',
        topic: 'collections-and-variations',
        title: 'Collections and Variations in MAS Studio',
        section: 'How do I add cards to an existing collection?',
        keywords: [
            'collection',
            'merch card collection',
            'variation',
            'locale variation',
            'grouped variation',
            'pzn',
            'personalization',
            'locale default',
            'parent fragment',
            'translation',
        ],
        text: "The AI assistant supports add_cards_to_collection: given the collection's UUID and a list of card paths, it appends the new paths to the collection's existing card list, de-duplicating so a card is never added twice, and asks for confirmation before executing. The backing action fetches the collection, merges the paths, and updates the fragment using its etag so concurrent edits are detected safely. The response includes a Studio deep link to view the updated collection.",
    },
    {
        id: 'collections-and-variations.md#3',
        topic: 'collections-and-variations',
        title: 'Collections and Variations in MAS Studio',
        section: 'How can I find collections and cards?',
        keywords: [
            'collection',
            'merch card collection',
            'variation',
            'locale variation',
            'grouped variation',
            'pzn',
            'personalization',
            'locale default',
            'parent fragment',
            'translation',
        ],
        text: 'The AI assistant supports search_collections, a read-only lookup that accepts an optional folder path, a text query, and limit and offset for paging. Cards are found with search_cards, which supports free text or title search plus surface, locale, tags, and OSI filters. A collection found through search can then be used as the target of add_cards_to_collection, or attached to a promotion in the Promotions editor.',
    },
    {
        id: 'collections-and-variations.md#4',
        topic: 'collections-and-variations',
        title: 'Collections and Variations in MAS Studio',
        section: 'What is a locale variation and what are the rules?',
        keywords: [
            'collection',
            'merch card collection',
            'variation',
            'locale variation',
            'grouped variation',
            'pzn',
            'personalization',
            'locale default',
            'parent fragment',
            'translation',
        ],
        text: 'A locale variation is a per-locale copy of a card whose parent is the locale default fragment, identified in the editor context by the default-locale-id. The rules enforced in Studio: there is exactly one variation per locale per fragment, so in the variation dialog any locale that already has a variation is disabled; a variation cannot be created from another variation — the error reads "Cannot create a variation from another variation. Please use the default locale fragment."; and if the backend reports that a variation already exists at a path, Studio links the existing fragment to the parent instead of creating a duplicate. In preview, fields left empty on a variation inherit the parent\'s value, while fields with a value override the parent for that field.',
    },
    {
        id: 'collections-and-variations.md#5',
        topic: 'collections-and-variations',
        title: 'Collections and Variations in MAS Studio',
        section: 'What is a grouped (pzn) variation?',
        keywords: [
            'collection',
            'merch card collection',
            'variation',
            'locale variation',
            'grouped variation',
            'pzn',
            'personalization',
            'locale default',
            'parent fragment',
            'translation',
        ],
        text: "A grouped variation is a personalization variation created under a parent fragment and driven by pzn tags rather than by locale. In the variation dialog it is only offered when the source fragment is the en_US fragment or a collection, and at least one pzn tag must be selected before it can be created. For cards, creating a grouped variation first resolves the fragment's OSI to its offer data; collections use a dedicated product arrangement code instead. Grouped variations are stored under a personalization (pzn) folder in the fragment path and appear in the fragment editor's variations panel next to locale variations and promo variations.",
    },
    {
        id: 'collections-and-variations.md#6',
        topic: 'collections-and-variations',
        title: 'Collections and Variations in MAS Studio',
        section: 'Which variation operations can the AI assistant perform?',
        keywords: [
            'collection',
            'merch card collection',
            'variation',
            'locale variation',
            'grouped variation',
            'pzn',
            'personalization',
            'locale default',
            'parent fragment',
            'translation',
        ],
        text: "Read-only operations: get_variations returns the variation graph for a fragment; get_card_with_variations returns a card plus its full variation tree; list_variation_locales lists the locales for which a card has variations; get_variation_parent returns the parent fragment of a variation; and find_untranslated_cards finds cards missing a variation in a target locale, optionally filtered by surface. State-changing operations, which always require confirmation: create_locale_variation creates a new locale variation given the parent card's UUID and a target locale, with an optional title; create_grouped_variation creates a grouped (pzn) variation under a parent, with optional title and tags.",
    },
    {
        id: 'offers-and-ost.md#0',
        topic: 'offers',
        title: 'Offers and the Offer Selector Tool (OST)',
        section: 'What is the difference between a card and an offer?',
        keywords: ['offer', 'OSI', 'offer selector', 'OST', 'price', 'AOS', 'product', 'link offer', 'arrangement code'],
        text: "A card is a content fragment authored in MAS Studio: the text, images, badges, and CTAs that users see. An offer is a commerce entity in Adobe's offer catalog (AOS) that defines a purchasable thing: the product, price, commitment, term, and customer segment. Cards never hardcode prices; instead a card stores an Offer Selector ID (OSI) that points at an offer. When the card renders on a page, the merch-card web component uses the OSI to fetch the current price from Adobe's Web Commerce Service (WCS) for the user's locale. If the price changes in the catalog, cards show the new price automatically without any re-authoring.",
    },
    {
        id: 'offers-and-ost.md#1',
        topic: 'offers',
        title: 'Offers and the Offer Selector Tool (OST)',
        section: 'What is an OSI (Offer Selector ID)?',
        keywords: ['offer', 'OSI', 'offer selector', 'OST', 'price', 'AOS', 'product', 'link offer', 'arrangement code'],
        text: "An OSI is the identifier stored on a card that selects its offer. It is a string of 7 to 64 characters made of letters, digits, underscores, and hyphens. An OSI is locale-agnostic: the same OSI works across all locales where the offer is valid, and currency, tax labels, and formatting are resolved automatically for the page's locale. An OSI is not the same thing as a raw offer ID, which is a 32-character hexadecimal string identifying one specific offer in AOS. The AI assistant can resolve an OSI to its underlying offer details, and can also fetch a single offer directly by its 32-character hex offer ID.",
    },
    {
        id: 'offers-and-ost.md#2',
        topic: 'offers',
        title: 'Offers and the Offer Selector Tool (OST)',
        section: 'What is the Offer Selector Tool (OST)?',
        keywords: ['offer', 'OSI', 'offer selector', 'OST', 'price', 'AOS', 'product', 'link offer', 'arrangement code'],
        text: "OST is Studio's built-in tool for finding an offer and attaching it to a card. Open it from the Offer Selector ID field in the card editor, search by product name, and narrow results by customer segment (individual, team, student), commitment, and term (monthly, annual). Selecting an offer inserts its OSI into the card; save the card afterwards so the OSI persists. The AI assistant can open OST for you on request, optionally pre-filled with search parameters.",
    },
    {
        id: 'offers-and-ost.md#3',
        topic: 'offers',
        title: 'Offers and the Offer Selector Tool (OST)',
        section: 'How do I link an offer to a card?',
        keywords: ['offer', 'OSI', 'offer selector', 'OST', 'price', 'AOS', 'product', 'link offer', 'arrangement code'],
        text: "In the editor, open OST from the OSI field, pick the offer, insert it, and save the card. Alternatively, ask the AI assistant to link a card to an offer by giving it the card ID and the OSI; it confirms with you before making the change. After linking, the assistant can validate card-offer consistency: it checks that the card's tags (plan type, offer type, customer segment) agree with the linked offer and reports any mismatches.",
    },
    {
        id: 'offers-and-ost.md#4',
        topic: 'offers',
        title: 'Offers and the Offer Selector Tool (OST)',
        section: 'How do I find offers or products without opening OST?',
        keywords: ['offer', 'OSI', 'offer selector', 'OST', 'price', 'AOS', 'product', 'link offer', 'arrangement code'],
        text: 'Ask the AI assistant. It can search the AOS offer catalog with filters such as product arrangement code, commitment, term, customer segment, market segment, offer type, country, locale, and price point. It can list Adobe products from the catalog and search them by name, fetch a single product by its exact product arrangement (PA) code, and compare all plan types available for one product arrangement side by side. These are read-only lookups, so no confirmation is needed.',
    },
    {
        id: 'offers-and-ost.md#5',
        topic: 'offers',
        title: 'Offers and the Offer Selector Tool (OST)',
        section: 'Can the AI assistant create a new offer selector?',
        keywords: ['offer', 'OSI', 'offer selector', 'OST', 'price', 'AOS', 'product', 'link offer', 'arrangement code'],
        text: 'Yes. To create an offer selector the assistant needs the product arrangement code, customer segment, market segment, and offer type; commitment, term, and price point are optional refinements. It asks for your confirmation, creates the selector in AOS, and returns the new OSI, which you or the assistant can then link to a card.',
    },
    {
        id: 'offers-and-ost.md#6',
        topic: 'offers',
        title: 'Offers and the Offer Selector Tool (OST)',
        section: 'What about offers that are not live yet (draft offers)?',
        keywords: ['offer', 'OSI', 'offer selector', 'OST', 'price', 'AOS', 'product', 'link offer', 'arrangement code'],
        text: 'OST searches published production offers by default. Offers that are still being onboarded exist in the DRAFT landscape and can be found by adding the commerce.landscape=DRAFT parameter to OST. A card authored against a draft offer switches automatically to the published version once the offer is released, so no re-authoring is needed. If you expect an offer to exist but cannot find it in either landscape, ask in the #merch-at-scale Slack channel.',
    },
    {
        id: 'placeholders.md#0',
        topic: 'placeholders',
        title: 'Placeholders in MAS Studio',
        section: 'What are placeholders in MAS Studio?',
        keywords: [
            'placeholder',
            'dictionary',
            'key',
            'value',
            'rich text',
            'locale string',
            'translation string',
            'token',
            'substitution',
        ],
        text: "Placeholders are reusable key/value text entries scoped to a surface and a locale. Each placeholder is stored as its own AEM content fragment (a dictionary entry) inside that surface and locale's dictionary folder, for example the dictionary folder under the surface's locale path. A placeholder fragment has a key, a plain text value, a rich text value, and a locReady flag. A special index fragment in the same dictionary folder keeps an entries list referencing every placeholder, and consumers resolve placeholders through that index. The Placeholders page in Studio shows the placeholders for the currently selected surface and locale in a searchable, sortable table with inline editing, publish, delete, and bulk delete.",
    },
    {
        id: 'placeholders.md#1',
        topic: 'placeholders',
        title: 'Placeholders in MAS Studio',
        section: 'How do I create a placeholder?',
        keywords: [
            'placeholder',
            'dictionary',
            'key',
            'value',
            'rich text',
            'locale string',
            'translation string',
            'token',
            'substitution',
        ],
        text: "Use the Create New Placeholder dialog on the Placeholders page. It asks for a Key, a Locale (a region picker that defaults to the current locale), an optional Rich Text toggle, and a Value. Key and Value are required, and the key is normalized as you type. On create, Studio creates the dictionary entry fragment under the surface and locale's dictionary path, tags it as draft, and registers it in the dictionary index fragment so it can be resolved; if updating the index fails, the creation is reported as failed. New placeholders start in draft status and must be published to go live. The AI assistant does not currently create or edit placeholders; use the Placeholders page.",
    },
    {
        id: 'placeholders.md#2',
        topic: 'placeholders',
        title: 'Placeholders in MAS Studio',
        section: 'How do rich text placeholders work?',
        keywords: [
            'placeholder',
            'dictionary',
            'key',
            'value',
            'rich text',
            'locale string',
            'translation string',
            'token',
            'substitution',
        ],
        text: "When the Rich Text toggle is enabled, the value is edited with a rich text editor that supports links and allows up to 500 characters, and the content is stored in the fragment's rich text value field instead of the plain value field. When a placeholder is resolved for a card, the plain value is used if present, otherwise the rich text value. Rich text lets a placeholder carry formatted content, such as a link inside card copy.",
    },
    {
        id: 'placeholders.md#3',
        topic: 'placeholders',
        title: 'Placeholders in MAS Studio',
        section: 'How do I edit, publish, or delete a placeholder?',
        keywords: [
            'placeholder',
            'dictionary',
            'key',
            'value',
            'rich text',
            'locale string',
            'translation string',
            'token',
            'substitution',
        ],
        text: 'Rows on the Placeholders page can be edited inline: key, value, and rich text value. Saving an edit marks the placeholder as draft again, so it must be republished for the change to go live. The publish action publishes the placeholder fragment and then republishes the dictionary index fragment so consumers pick up the change; a placeholder that is already published is skipped. Delete asks for confirmation and warns the action cannot be undone; it removes the placeholder from the dictionary index first, then deletes the fragment. Bulk delete works on the current table selection.',
    },
    {
        id: 'placeholders.md#4',
        topic: 'placeholders',
        title: 'Placeholders in MAS Studio',
        section: 'How are placeholders resolved on cards?',
        keywords: [
            'placeholder',
            'dictionary',
            'key',
            'value',
            'rich text',
            'locale string',
            'translation string',
            'token',
            'substitution',
        ],
        text: "Card fields may contain tokens like {{key}}, where the key consists of letters, digits, hyphens and underscores. When the fragment pipeline serves a card, its replace step loads the dictionary for the request's surface and regional locale by fetching the dictionary index fragment and its references, builds a key-to-value map, and substitutes each token. Dictionaries can chain to a parent dictionary, and the child's entries take precedence over the parent's. A placeholder that exists with an empty value is treated as intentionally empty, which is different from a missing key.",
    },
    {
        id: 'placeholders.md#5',
        topic: 'placeholders',
        title: 'Placeholders in MAS Studio',
        section: 'Why is my placeholder not showing up on a card?',
        keywords: [
            'placeholder',
            'dictionary',
            'key',
            'value',
            'rich text',
            'locale string',
            'translation string',
            'token',
            'substitution',
        ],
        text: "Common causes verified in the implementation: the placeholder or the dictionary index was not published — publishing a placeholder must also republish the index, which Studio's publish action does automatically; the placeholder was created in a different surface or locale than the one the card is served for, since dictionaries are resolved per surface and per regional locale; the resolved dictionary is cached for about five minutes, so a just-published placeholder can take a short time to appear; or the token in the card copy does not exactly match the key — tokens only allow word characters, hyphens and underscores inside double curly braces.",
    },
    {
        id: 'promotions.md#0',
        topic: 'promotions',
        title: 'Promotions in MAS Studio',
        section: 'What is a promotion in MAS Studio?',
        keywords: [
            'promotion',
            'promo',
            'promo code',
            'campaign',
            'project',
            'discount',
            'offer substitution',
            'promo variation',
            'schedule',
            'publish promotion',
        ],
        text: 'A promotion (called a "project" in parts of the UI) is an AEM content fragment managed from the Promotions area of MAS Studio. It carries a title, a promo code, a start date and an end date, one or more promotion tags (mas:promotion), target geos (country tags), target surfaces, a list of attached offers (offer selector IDs), and attached fragments — merch cards and card collections. Dates entered in the editor are stored as UTC ISO timestamps. The promotions list can be filtered by lifecycle status such as draft, scheduled, active and expired.',
    },
    {
        id: 'promotions.md#1',
        topic: 'promotions',
        title: 'Promotions in MAS Studio',
        section: 'How do I create a promotion?',
        keywords: [
            'promotion',
            'promo',
            'promo code',
            'campaign',
            'project',
            'discount',
            'offer substitution',
            'promo variation',
            'schedule',
            'publish promotion',
        ],
        text: 'Open the Promotions editor and start a new project. Fill in the title, promo code, start date and end date, add at least one promotion tag, at least one geo and at least one surface, then attach items. Offers are attached by OSI through the Offer Selector Tool; cards and collections are attached through the items picker, which accepts search text, Studio deep links, DAM paths, and fragment UUIDs. Saving creates the promotion fragment in AEM; on success Studio shows "Project successfully created." and keeps you in the editor. The editor\'s quick actions are Save, Duplicate, Publish, Unpublish, Copy link, Lock project, and Delete.',
    },
    {
        id: 'promotions.md#2',
        topic: 'promotions',
        title: 'Promotions in MAS Studio',
        section: 'What fields are required before a promotion can be saved?',
        keywords: [
            'promotion',
            'promo',
            'promo code',
            'campaign',
            'project',
            'discount',
            'offer substitution',
            'promo variation',
            'schedule',
            'publish promotion',
        ],
        text: 'Validation requires, in this order: a Title, a Promo Code, a Start Date, an End Date, at least one Promotion tag, at least one Geo, at least one Surface, and at least one attached fragment or collection. Each missing requirement produces its own message, for example "Please enter a Promo Code." or "Please add at least one Geo." The editor also tracks whether the attached items and offers differ from what is saved on the fragment, and prompts to discard changes if you try to leave the page with unsaved edits.',
    },
    {
        id: 'promotions.md#3',
        topic: 'promotions',
        title: 'Promotions in MAS Studio',
        section: 'What do the promotion statuses mean?',
        keywords: [
            'promotion',
            'promo',
            'promo code',
            'campaign',
            'project',
            'discount',
            'offer substitution',
            'promo variation',
            'schedule',
            'publish promotion',
        ],
        text: 'Status is computed from the promotion\'s dates and its AEM publication status. "unknown" means the start or end date is missing or invalid. "expired" means the end date is in the past. "modified" means it was published but changed since publishing. "draft" means it has never been published. "scheduled" means it is published and the start date is in the future. "active" means it is published and currently inside the date window. In the promotions list filter, a modified promotion is shown as scheduled when its start date is in the future, otherwise as active.',
    },
    {
        id: 'promotions.md#4',
        topic: 'promotions',
        title: 'Promotions in MAS Studio',
        section: 'How do I publish or schedule a promotion?',
        keywords: [
            'promotion',
            'promo',
            'promo code',
            'campaign',
            'project',
            'discount',
            'offer substitution',
            'promo variation',
            'schedule',
            'publish promotion',
        ],
        text: 'One action covers both: if the start date is in the future the promotion is scheduled, otherwise it is published immediately. Publishing is blocked when there are unsaved changes ("Save your changes before publishing."), when the start date is missing, when the promotion has expired ("This promotion has ended. Update the dates to publish again."), or when it is already published and unmodified. Before publishing, Studio checks the attached promo variations; if some are unpublished it asks whether to publish them together with the project and, when confirmed, publishes the promotion and those variations in a single AEM request. If some variations could not be included, a toast reports how many were skipped. Unpublish is available for published promotions.',
    },
    {
        id: 'promotions.md#5',
        topic: 'promotions',
        title: 'Promotions in MAS Studio',
        section: 'What are promo variations and where are they stored?',
        keywords: [
            'promotion',
            'promo',
            'promo code',
            'campaign',
            'project',
            'discount',
            'offer substitution',
            'promo variation',
            'schedule',
            'publish promotion',
        ],
        text: "A promo variation is a promotion-specific copy of a default card. It lives under the surface and locale's promotions folder, in a subfolder named after the promotion; the folder name is derived from the promotion's mas:promotion tag. A fragment is recognized as a promo variation either by its path (inside the promotions folder) or by carrying a mas:promotion tag. Studio can resolve the default fragment path back from a promo variation path and the reverse, and the fragment editor's variations panel lists promo variations alongside locale variations and grouped variations.",
    },
    {
        id: 'promotions.md#6',
        topic: 'promotions',
        title: 'Promotions in MAS Studio',
        section: 'How do promo code exceptions and offer substitutions work?',
        keywords: [
            'promotion',
            'promo',
            'promo code',
            'campaign',
            'project',
            'discount',
            'offer substitution',
            'promo variation',
            'schedule',
            'publish promotion',
        ],
        text: "A promotion has a single default promo code, but the promo codes manager lets you override it per offer and per country, and also substitute a different offer selector for a base offer in specific countries. These exceptions and substitutions are serialized into the promotion's offers field together with the plain selected offer IDs. The available countries come from the promotion's geos. When you remove an offer from a promotion, attached cards and collections that no longer match any remaining offer's product code tags are removed from the selection after a confirmation message.",
    },
    {
        id: 'promotions.md#7',
        topic: 'promotions',
        title: 'Promotions in MAS Studio',
        section: 'Can the AI assistant manage promotions?',
        keywords: [
            'promotion',
            'promo',
            'promo code',
            'campaign',
            'project',
            'discount',
            'offer substitution',
            'promo variation',
            'schedule',
            'publish promotion',
        ],
        text: 'The AI assistant does not currently create, edit, publish or unpublish promotions — there are no promotion intents in its registry. It can help prepare promotion content: it can search cards and collections, resolve and search offers, create an offer selector (returning an OSI that can be attached to a promotion), and open the Offer Selector Tool. Creating and publishing the promotion itself must be done in the Promotions editor in Studio.',
    },
    {
        id: 'studio-basics.md#0',
        topic: 'studio',
        title: 'MAS Studio Basics',
        section: 'What is Merch at Scale (M@S)?',
        keywords: [
            'MAS',
            'Merch at Scale',
            'Studio',
            'Odin',
            'AEM',
            'fragment',
            'surface',
            'locale',
            'adobe.com',
            'architecture',
        ],
        text: "Merch at Scale is Adobe's platform for authoring, managing, and delivering merchandising content — merch cards with product information, live pricing, and purchase CTAs — across Adobe's digital properties. Instead of hardcoding product cards into each page, teams author a card once in MAS Studio and the same card can be delivered to adobe.com, Creative Cloud Desktop, Adobe Home, Adobe Express, and Unified Checkout. Prices are fetched from Adobe's commerce services when the card renders, so pricing stays current everywhere without re-authoring.",
    },
    {
        id: 'studio-basics.md#1',
        topic: 'studio',
        title: 'MAS Studio Basics',
        section: 'What is MAS Studio?',
        keywords: [
            'MAS',
            'Merch at Scale',
            'Studio',
            'Odin',
            'AEM',
            'fragment',
            'surface',
            'locale',
            'adobe.com',
            'architecture',
        ],
        text: 'MAS Studio is the web application at https://mas.adobe.com/studio.html where merch cards are created, edited, and published. It offers a visual editor with live preview, a folder tree organized by surface, table and rendered views of your cards, search and filtering, integration with the Offer Selector Tool for pricing, a publish workflow, and an AI assistant chat panel. You sign in with your Adobe corporate account through IMS, and what you can see and do is governed by IAM group permissions.',
    },
    {
        id: 'studio-basics.md#2',
        topic: 'studio',
        title: 'MAS Studio Basics',
        section: 'Where does card content live?',
        keywords: [
            'MAS',
            'Merch at Scale',
            'Studio',
            'Odin',
            'AEM',
            'fragment',
            'surface',
            'locale',
            'adobe.com',
            'architecture',
        ],
        text: "Cards are stored as content fragments in Odin, Adobe's internal Adobe Experience Manager (AEM) instance for structured content. All MAS content lives under the /content/dam/mas/ path, organized into folders by surface and locale. A fragment is structured data — named fields such as title, description, prices, ctas, and variant — not a rendered page; rendering happens later in the merch-card web component on the consuming page. Always create and edit MAS fragments through MAS Studio rather than directly in the AEM authoring UI, so the card structure stays valid.",
    },
    {
        id: 'studio-basics.md#3',
        topic: 'studio',
        title: 'MAS Studio Basics',
        section: 'How does a card reach adobe.com?',
        keywords: [
            'MAS',
            'Merch at Scale',
            'Studio',
            'Odin',
            'AEM',
            'fragment',
            'surface',
            'locale',
            'adobe.com',
            'architecture',
        ],
        text: "First, an author creates and publishes the card in MAS Studio, which publishes the content fragment in Odin. Second, an adobe.com page includes the merch-card web component referencing that fragment. Third, when the page loads, the component fetches the fragment as JSON from the MAS delivery endpoint at https://www.adobe.com/mas/io/fragment, which runs a processing pipeline including locale resolution, placeholder replacement, and pricing integration. Fourth, if the card has an Offer Selector ID, the current price is fetched from the Web Commerce Service (WCS) for the user's locale. Responses are cached at the Akamai edge for performance, so a just-published change can take a short while to appear.",
    },
    {
        id: 'studio-basics.md#4',
        topic: 'studio',
        title: 'MAS Studio Basics',
        section: 'What are surfaces and locales in MAS?',
        keywords: [
            'MAS',
            'Merch at Scale',
            'Studio',
            'Odin',
            'AEM',
            'fragment',
            'surface',
            'locale',
            'adobe.com',
            'architecture',
        ],
        text: 'Surfaces are the destinations where cards render: acom (adobe.com), ccd (Creative Cloud Desktop), adobe-home (Adobe Home), commerce (Unified Checkout), and express (Adobe Express), plus a sandbox area for testing. Locales use codes like en_US or fr_FR (language plus country), and content folders follow the pattern /content/dam/mas/ then surface then locale. A card has a locale-default parent fragment, and each locale can hold exactly one variation of it for translated or region-specific content. Prices localize automatically through the offer system, but card text does not — translated text requires locale variations, which can be produced through translation projects.',
    },
    {
        id: 'studio-basics.md#5',
        topic: 'studio',
        title: 'MAS Studio Basics',
        section: 'What can the AI assistant in Studio do?',
        keywords: [
            'MAS',
            'Merch at Scale',
            'Studio',
            'Odin',
            'AEM',
            'fragment',
            'surface',
            'locale',
            'adobe.com',
            'architecture',
        ],
        text: "The assistant can search cards by title, content, tags, surface, locale, or linked offer ID; fetch a card's contents; open a card in the editor; and copy a deep link to a card. It can publish, unpublish, update, and duplicate cards, run bulk updates and bulk publishes with dry-run previews, create and inspect locale variations, create collections and add cards to them, and create tags. On the commerce side it can search products and offers, resolve OSIs, create offer selectors, link offers to cards, and validate card-offer consistency. It also supports translation coverage reports, finding untranslated cards, translation projects, a guided flow for creating new product release cards, and opening the Offer Selector Tool. Every state-changing action asks for your explicit confirmation before it runs.",
    },
    {
        id: 'translations.md#0',
        topic: 'translations',
        title: 'Translations in MAS Studio',
        section: 'How do I create a translation project?',
        keywords: [
            'translation',
            'translate',
            'localize',
            'localization',
            'locale',
            'language',
            'translation project',
            'rollout',
        ],
        text: 'Open the Translations page from the MAS Studio side navigation and click the "Create project" button. This opens the translation project editor, where you give the project a title, choose one or more target locales, and add the content to translate: cards (fragments), placeholders, and collections. A project cannot be saved until it has a title, at least one target locale, and at least one selected item. The title is used as the localization task name, so it must be at most 255 characters, contain at least one letter or number, and use only letters, numbers, hyphens, underscores, and dots (consecutive dots are not allowed). You can also ask the AI assistant to "create a translation project" with a title and target locales; it will ask for confirmation before creating it, and can optionally include specific card paths.',
    },
    {
        id: 'translations.md#1',
        topic: 'translations',
        title: 'Translations in MAS Studio',
        section: 'What does a translation project contain?',
        keywords: [
            'translation',
            'translate',
            'localize',
            'localization',
            'locale',
            'language',
            'translation project',
            'rollout',
        ],
        text: 'A translation project is stored as a content fragment with these fields: title, status, fragments (the card paths to translate), placeholders, collections, targetLocales, submissionDate, and projectType. Target locales use the underscore format such as fr_FR, de_DE, or ja_JP. The projectType is "translation" by default; a second type, "rollout", exists for rollout-only projects that copy content to target locales without sending it for translation. The Translations page lists all projects in a table showing title, status, who last modified the project, and the "Sent on" date (the submission date, sortable). From the row action menu you can edit or delete a project; deleting is permanent.',
    },
    {
        id: 'translations.md#2',
        topic: 'translations',
        title: 'Translations in MAS Studio',
        section: 'How do I send a translation project for localization?',
        keywords: [
            'translation',
            'translate',
            'localize',
            'localization',
            'locale',
            'language',
            'translation project',
            'rollout',
        ],
        text: 'After creating and saving the project, use the send-for-localization action in the translation project editor. Studio calls the translation-project-start backend action with the project ID and the current surface, authenticated with your IMS token. On success the submission date is stamped on the project, its status becomes Pending, and the project becomes read-only in the editor. The AI assistant can also do this: ask it to "submit translation project" with the project ID (submit_translation_project), and it will ask for confirmation first since submission changes state.',
    },
    {
        id: 'translations.md#3',
        topic: 'translations',
        title: 'Translations in MAS Studio',
        section: 'What do the translation project statuses mean?',
        keywords: [
            'translation',
            'translate',
            'localize',
            'localization',
            'locale',
            'language',
            'translation project',
            'rollout',
        ],
        text: 'The status column on the Translations page maps internal states to labels. "Pending" (internal status QUEUED) means the submission was accepted and the job is waiting in the queue. "Running" (RUNNING) means the job is being processed, including content synchronization. "Sent to loc" (ASYNC_PROCESSING) means the content has been handed off to the localization service and is out for translation. "Failed" (FAILED) means the job did not complete; the project can be inspected and resubmitted. You can also ask the AI assistant to "check translation status" for a project ID or to "list translation projects", optionally filtered by status.',
    },
    {
        id: 'translations.md#4',
        topic: 'translations',
        title: 'Translations in MAS Studio',
        section: 'What happens after I submit a translation project?',
        keywords: [
            'translation',
            'translate',
            'localize',
            'localization',
            'locale',
            'language',
            'translation project',
            'rollout',
        ],
        text: 'Submission is asynchronous. The translation-project-start action validates the request, marks the project QUEUED with a submission date, stores the job payload, enqueues the job, and invokes a dispatcher action in the background, returning immediately. The worker then runs a sync stage before localization: placeholder entries are added to the dictionary index of each target locale, and for grouped (pzn) variations the parent fragments in each target locale are updated to reference the translated variations so they stay linked. After syncing, the worker sends the localization request to the AEM/Odin localization endpoint with the task name, the content fragment paths, and the target locales. The translation flow is determined per surface (for example transcreation) unless human translation is configured.',
    },
    {
        id: 'translations.md#5',
        topic: 'translations',
        title: 'Translations in MAS Studio',
        section: 'What is a rollout project?',
        keywords: [
            'translation',
            'translate',
            'localize',
            'localization',
            'locale',
            'language',
            'translation project',
            'rollout',
        ],
        text: 'A rollout project is a translation project whose projectType field is set to "rollout". Instead of sending content out for translation, the backend sends the selected content paths and target locales to the Odin locale-sync endpoint, which copies the content into the target locales as-is. This is useful when you need locale copies of fragments without changing the text, for example when the content is language-neutral or will be edited manually per locale. Rollout projects go through the same submission pipeline as translation projects: they are queued, synced, and dispatched asynchronously, and the same status labels apply on the Translations page.',
    },
    {
        id: 'translations.md#6',
        topic: 'translations',
        title: 'Translations in MAS Studio',
        section: 'What can the AI assistant do with translations?',
        keywords: [
            'translation',
            'translate',
            'localize',
            'localization',
            'locale',
            'language',
            'translation project',
            'rollout',
        ],
        text: 'The assistant supports several translation intents. Read-only: "find untranslated cards" for a target locale (find_untranslated_cards, optionally scoped to a surface), "translation coverage report" across locales (translation_coverage_report), "get translation project" details by ID, "list translation projects" optionally by status, and "check translation status" of a job. State-changing, always confirmed before executing: "create a translation project" with a title and target locales (create_translation_project) and "submit translation project" by ID (submit_translation_project). For example, you can ask "which cards are missing a fr_FR variation in acom?" and then create a translation project for the results.',
    },
    {
        id: 'translations.md#7',
        topic: 'translations',
        title: 'Translations in MAS Studio',
        section: 'Are prices and offers translated too?',
        keywords: [
            'translation',
            'translate',
            'localize',
            'localization',
            'locale',
            'language',
            'translation project',
            'rollout',
        ],
        text: 'No, and they do not need to be. Card prices come from the offer selector (OSI), which adapts automatically to the page locale: currency, tax labels, and checkout links are resolved at render time by the commerce backend. The same OSI works across locales as long as the offer is valid there. Commerce placeholders are likewise resolved by backend locale logic rather than translated. What translation projects handle is the authored card content itself — titles, descriptions, and other text fields — which is not auto-translated and must go through a translation project (or be authored separately per locale).',
    },
    {
        id: 'troubleshooting.md#0',
        topic: 'troubleshooting',
        title: 'Troubleshooting MAS Studio',
        section: 'Why is my card not showing on the page (fragment not found)?',
        keywords: ['error', 'fragment not found', 'publish failed', 'price not showing', '404', '401', '403', 'help', 'slack'],
        text: 'A "fragment not found" or 404 error means the delivery API cannot find the fragment at the requested path. Check three things. First, the card must be Published, not Draft or Modified — unpublished fragments are not delivered. Second, the fragment path must be exact and is case-sensitive; it starts with /content/dam/mas/. Third, test delivery directly by opening https://www.adobe.com/mas/io/fragment with the path parameter set to your fragment path — a working fragment returns JSON. If the card was just published, edge caching can briefly serve stale results; hard refresh and retry after a minute or two. You can also ask the AI assistant to search for the card to confirm it exists and check its status.',
    },
    {
        id: 'troubleshooting.md#1',
        topic: 'troubleshooting',
        title: 'Troubleshooting MAS Studio',
        section: 'Why is the price not showing on my card?',
        keywords: ['error', 'fragment not found', 'publish failed', 'price not showing', '404', '401', '403', 'help', 'slack'],
        text: "Prices are fetched at render time from the Web Commerce Service (WCS) using the card's Offer Selector ID (OSI). Verify the OSI field has a value and that the card was saved after inserting it — the OSI only persists after a save. Then verify the offer is valid for the page's locale and country and that today falls within its availability dates; a WCS response of 200 with an empty body usually means the offer is not available for that locale. In the browser network tab, look for requests containing web_commerce_artifact and inspect the response. The AI assistant can resolve the OSI to its offer details so you can confirm the offer exists, and it can validate that the card and its linked offer are consistent.",
    },
    {
        id: 'troubleshooting.md#2',
        topic: 'troubleshooting',
        title: 'Troubleshooting MAS Studio',
        section: "Why can't I publish my card?",
        keywords: ['error', 'fragment not found', 'publish failed', 'price not showing', '404', '401', '403', 'help', 'slack'],
        text: "The most common causes are missing permissions, validation errors, or a temporary backend issue. Publishing requires a publisher role through your IAM group membership — being able to edit does not imply being able to publish. Validation errors also block publishing: check for red error indicators and fill all required fields for the card's variant. If permissions and validation are fine, it may be a temporary issue in the AEM backend; retry later, and if it persists ask in the #merch-at-scale Slack channel. For publishing many cards, the AI assistant can show a preview of exactly which cards a bulk publish would affect before running it.",
    },
    {
        id: 'troubleshooting.md#3',
        topic: 'troubleshooting',
        title: 'Troubleshooting MAS Studio',
        section: 'What do 401 and 403 errors mean?',
        keywords: ['error', 'fragment not found', 'publish failed', 'price not showing', '404', '401', '403', 'help', 'slack'],
        text: "A 401 means your IMS session token is expired or invalid: sign out of Studio and sign back in; clearing the browser's session storage for the site also helps. A 403 means you are authenticated but lack permission for the action: check your IAM group membership. If you can log in but see no content at all, you are likely missing the surface-specific author group for the surface you are browsing. Request the needed groups through Adobe's IAM system, allow time for provisioning, then log out and back in.",
    },
    {
        id: 'troubleshooting.md#4',
        topic: 'troubleshooting',
        title: 'Troubleshooting MAS Studio',
        section: 'Why does OST show no results for my search?',
        keywords: ['error', 'fragment not found', 'publish failed', 'price not showing', '404', '401', '403', 'help', 'slack'],
        text: 'Several causes are common. The offer may not be valid for the locale you are authoring in — offers are onboarded per country. Its availability dates may exclude today. It may still be a draft offer, which only appears when searching the DRAFT landscape (add the commerce.landscape=DRAFT parameter). Or it may not exist yet. The AI assistant can search the offer catalog with filters and list matching products, which quickly confirms whether the offer exists at all before you dig further.',
    },
    {
        id: 'troubleshooting.md#5',
        topic: 'troubleshooting',
        title: 'Troubleshooting MAS Studio',
        section: 'The AI assistant gave an error or a wrong result — what should I do?',
        keywords: ['error', 'fragment not found', 'publish failed', 'price not showing', '404', '401', '403', 'help', 'slack'],
        text: 'Retry the request once — transient backend errors happen. If the conversation seems stuck in the middle of a flow, ask to start over; this clears the chat and any in-progress flow state. Note that the assistant always asks for confirmation before publishing, updating, or creating anything, so an error never means something was changed without your approval. If a problem persists, report it in the #merch-at-scale Slack channel with what you asked and roughly when.',
    },
    {
        id: 'troubleshooting.md#6',
        topic: 'troubleshooting',
        title: 'Troubleshooting MAS Studio',
        section: 'Where do I get help?',
        keywords: ['error', 'fragment not found', 'publish failed', 'price not showing', '404', '401', '403', 'help', 'slack'],
        text: 'The #merch-at-scale Slack channel is the main channel for all MAS questions: authoring help, Studio bugs, publishing problems, and access requests. The team has a no-direct-message policy, so post in the channel rather than messaging individuals — answers in channel help everyone. For pricing and offer catalog data issues use #catalog-support, and for adobe.com page integration questions use #milo-dev. Bugs are tracked in the Jira MWPW project; a good report includes steps to reproduce, the fragment path, the OSI if pricing-related, the environment, and screenshots.',
    },
];
