export default {
    name: 'MAS Studio Mnemonic Modal Edit Tests',
    features: [
        {
            tcid: '0',
            name: '@studio-mnemonic-modal-open',
            path: '/studio.html',
            tags: '@mas-studio @mnemonic-modal @regression',
            browserParams: '#page=content&path=nala&query=',
            data: {
                cardid: '5a5ca143-a417-4087-b466-5b72ac68a830',
                cardVariant: 'plans',
                currentIcon: 'https://www.adobe.com/content/dam/shared/images/product-icons/svg/acrobat-pro.svg',
                modalTitle: 'Edit Mnemonic Icon',
            },
        },
        {
            tcid: '1',
            name: '@studio-mnemonic-modal-select-product',
            path: '/studio.html',
            tags: '@mas-studio @mnemonic-modal @smoke',
            browserParams: '#page=content&path=nala&query=',
            data: {
                cardid: '5a5ca143-a417-4087-b466-5b72ac68a830',
                productName: 'Photoshop',
                productId: 'photoshop',
                newIconURL: 'https://www.adobe.com/cc-shared/assets/img/product-icons/svg/photoshop.svg',
                altText: 'Adobe Photoshop',
                linkURL: 'https://www.adobe.com/products/photoshop.html',
            },
        },
        {
            tcid: '2',
            name: '@studio-mnemonic-modal-select-illustrator',
            path: '/studio.html',
            tags: '@mas-studio @mnemonic-modal @smoke',
            browserParams: '#page=content&path=nala&query=',
            data: {
                cardid: '5a5ca143-a417-4087-b466-5b72ac68a830',
                productName: 'Illustrator',
                productId: 'illustrator',
                newIconURL: 'https://www.adobe.com/cc-shared/assets/img/product-icons/svg/illustrator.svg',
                altText: 'Adobe Illustrator',
                linkURL: 'https://www.adobe.com/products/illustrator.html',
            },
        },
        {
            tcid: '3',
            name: '@studio-mnemonic-modal-custom-url',
            path: '/studio.html',
            tags: '@mas-studio @mnemonic-modal @regression',
            browserParams: '#page=content&path=nala&query=',
            data: {
                cardid: '5a5ca143-a417-4087-b466-5b72ac68a830',
                customIconURL: 'https://www.adobe.com/cc-shared/assets/img/product-icons/svg/firefly.svg',
                altText: 'Custom Product Icon',
                linkURL: 'https://www.adobe.com/products/firefly.html',
            },
        },
        {
            tcid: '4',
            name: '@studio-mnemonic-modal-validation',
            path: '/studio.html',
            tags: '@mas-studio @mnemonic-modal @regression',
            browserParams: '#page=content&path=nala&query=',
            data: {
                cardid: '5a5ca143-a417-4087-b466-5b72ac68a830',
                emptyURL: '',
                validURL: 'https://www.adobe.com/cc-shared/assets/img/product-icons/svg/acrobat-pro.svg',
            },
        },
        {
            tcid: '5',
            name: '@studio-mnemonic-modal-tab-switch',
            path: '/studio.html',
            tags: '@mas-studio @mnemonic-modal @regression',
            browserParams: '#page=content&path=nala&query=',
            data: {
                cardid: '5a5ca143-a417-4087-b466-5b72ac68a830',
                productName: 'Premiere Pro',
                productId: 'premiere-pro',
                customURL: 'https://example.com/custom-icon.svg',
            },
        },
        {
            tcid: '6',
            name: '@studio-mnemonic-modal-all-products',
            path: '/studio.html',
            tags: '@mas-studio @mnemonic-modal @comprehensive',
            browserParams: '#page=content&path=nala&query=',
            data: {
                cardid: '5a5ca143-a417-4087-b466-5b72ac68a830',
                products: [
                    { id: 'creative-cloud', name: 'Creative Cloud' },
                    { id: 'photoshop', name: 'Photoshop' },
                    { id: 'lightroom', name: 'Lightroom' },
                    { id: 'illustrator', name: 'Illustrator' },
                    { id: 'indesign', name: 'InDesign' },
                    { id: 'premiere-pro', name: 'Premiere Pro' },
                    { id: 'after-effects', name: 'After Effects' },
                    { id: 'acrobat-pro', name: 'Acrobat Pro' },
                ],
            },
        },
    ],
};
