export default {
    FeatureName: 'M@S Studio CCD Suggested',
    features: [
        {
            tcid: '0',
            name: '@studio-suggested-variant-change-to-slice',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
            },
            browserParams: '#page=content&path=nala&query=',
            tags: '@mas-studio @ccd @ccd-edit @ccd-suggested @ccd-suggested-edit',
        },
        {
            tcid: '1',
            name: '@studio-suggested-edit-discard-title',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                title: 'Automation Test Card',
                newTitle: 'Change title',
            },
            browserParams: '#page=content&path=nala&query=',
            tags: '@mas-studio @ccd @ccd-edit @ccd-suggested @ccd-suggested-edit',
        },
        {
            tcid: '2',
            name: '@studio-suggested-edit-discard-eyebrow',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                subtitle: 'do not edit',
                newSubtitle: 'Change subtitle',
            },
            browserParams: '#page=content&path=nala&query=',
            tags: '@mas-studio @ccd @ccd-edit @ccd-suggested @ccd-suggested-edit',
        },
        {
            tcid: '3',
            name: '@studio-suggested-edit-discard-description',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                description: 'MAS repo validation card for Nala tests',
                newDescription: 'New Test Description',
            },
            browserParams: '#page=content&path=nala&query=',
            tags: '@mas-studio @ccd @ccd-edit @ccd-suggested @ccd-suggested-edit',
        },
        {
            tcid: '4',
            name: '@studio-suggested-edit-discard-mnemonic',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                iconURL: 'https://www.adobe.com/content/dam/shared/images/product-icons/svg/photoshop.svg',
                newIconURL: 'https://www.adobe.com/content/dam/shared/images/product-icons/svg/illustrator.svg',
            },
            browserParams: '#page=content&path=nala&query=',
            tags: '@mas-studio @ccd @ccd-edit @ccd-suggested @ccd-suggested-edit',
        },
        {
            tcid: '5',
            name: '@studio-suggested-edit-discard-background',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                newBackgroundURL:
                    'https://milo.adobe.com/assets/img/commerce/media_1d63dab9ee1edbf371d6f0548516c9e12b3ea3ff4.png',
            },
            browserParams: '#page=content&path=nala&query=',
            tags: '@mas-studio @ccd @ccd-edit @ccd-suggested @ccd-suggested-edit',
        },
        {
            tcid: '6',
            name: '@studio-suggested-edit-discard-price',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                price: 'US$17.24/mo',
                strikethroughPrice: 'US$34.49/mo',
                newPrice: 'US$17.24/moper license',
                newStrikethroughPrice: 'US$34.49/moper license',
            },
            browserParams: '#page=content&path=nala&query=',
            tags: '@mas-studio @ccd @ccd-edit @ccd-suggested @ccd-suggested-edit',
        },
        {
            tcid: '7',
            name: '@studio-suggested-edit-discard-cta-ost',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
                ctaText: 'Buy now',
                newCtaOption: 'Save now',
                newCtaText: 'save-now',
                ucv3: 'commerce.adobe.com/store/email',
                country: 'US',
                ctx: 'fp',
                lang: 'en',
                client: 'adobe_com',
                promo: 'UMRM2MUSPr501YOC',
            },
            browserParams: '#page=content&path=nala&query=',
            tags: '@mas-studio @ccd @ccd-edit @ccd-suggested @ccd-suggested-edit',
        },
        {
            tcid: '8',
            name: '@studio-suggested-edit-discard-cta-label',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
                ctaText: 'Buy now',
                newCtaText: 'Buy now 2',
            },
            browserParams: '#page=content&path=nala&query=',
            tags: '@mas-studio @ccd @ccd-edit @ccd-suggested @ccd-suggested-edit',
        },
        {
            tcid: '9',
            name: '@studio-suggested-edit-discard-price-promo',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                promo: 'UMRM2MUSPr501YOC',
                newPromo: 'testpromo',
            },
            browserParams: '#page=content&path=nala&query=',
            tags: '@mas-studio @ccd @ccd-edit @ccd-suggested @ccd-suggested-edit',
        },
        {
            tcid: '10',
            name: '@studio-suggested-edit-discard-cta-promo',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                promo: 'UMRM2MUSPr501YOC',
                newPromo: 'testpromo',
                ucv3: 'commerce.adobe.com/store/email',
                country: 'US',
                ctx: 'fp',
                lang: 'en',
                client: 'adobe_com',
            },
            browserParams: '#page=content&path=nala&query=',
            tags: '@mas-studio @ccd @ccd-edit @ccd-suggested @ccd-suggested-edit',
        },
        {
            tcid: '11',
            name: '@studio-suggested-variant-change-to-trybuywidget',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
            },
            browserParams: '#page=content&path=nala&query=',
            tags: '@mas-studio @ccd @ccd-edit @ccd-suggested @ccd-suggested-edit',
        },
        {
            tcid: '12',
            name: '@studio-suggested-add-osi',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
                productCodeTag: 'product_code/phsp',
                offerTypeTag: 'offer_type/base',
                marketSegmentsTag: 'market_segments/com',
                planTypeTag: 'plan_type/abm',
            },
            browserParams: '#page=content&path=nala&query=',
            tags: '@mas-studio @ccd @ccd-edit @ccd-suggested @ccd-suggested-edit',
        },
        {
            tcid: '13',
            name: '@studio-suggested-edit-discard-osi',
            path: '/studio.html',
            data: {
                cardid: 'cc85b026-240a-4280-ab41-7618e65daac4',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
                productCodeTag: 'product_code/phsp',
                offerTypeTag: 'offer_type/base',
                marketSegmentsTag: 'market_segments/com',
                planTypeTag: 'plan_type/abm',
                newosi: '1RwmqQ0NVsrtYr1bj05lZCJBavU6JGa67djrwKE8k8o',
                newProductCodeTag: 'product_code/ccsn',
                newPlanTypeTag: 'plan_type/puf',
                newOfferTypeTag: 'offer_type/trial',
                newMarketSegmentsTag: 'market_segments/edu',
            },
            browserParams: '#page=content&path=nala&query=',
            tags: '@mas-studio @ccd @ccd-edit @ccd-suggested @ccd-suggested-edit',
        },
        {
            tcid: '14',
            name: '@studio-suggested-edit-discard-cta-variant',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
                variant: 'primary-outline',
                ctaCSS: {
                    color: 'rgb(34, 34, 34)',
                },
                newVariant: 'accent',
                newCtaCSS: {
                    'background-color': 'rgb(2, 101, 220)',
                    color: 'rgb(255, 255, 255)',
                },
            },
            browserParams: '#page=content&path=nala&query=',
            tags: '@mas-studio @ccd @ccd-edit @ccd-suggested @ccd-suggested-edit',
        },
        {
            tcid: '15',
            name: '@studio-suggested-edit-discard-cta-checkout-params',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                osi: 'A1xn6EL4pK93bWjM8flffQpfEL-bnvtoQKQAvkx574M',
                checkoutParams: {
                    mv: '1',
                    promoid: 'ABC123',
                    mv2: '2',
                },
            },
            browserParams: '#page=content&path=nala&query=',
            tags: '@mas-studio @ccd @ccd-edit @ccd-suggested @ccd-suggested-edit',
        },
        {
            tcid: '16',
            name: '@studio-suggested-edit-discard-analytics-ids',
            path: '/studio.html',
            data: {
                cardid: '206a8742-0289-4196-92d4-ced99ec4191e',
                analyticsID: 'buy-now',
                daaLL: 'buy-now-1',
                daaLH: 'phsp',
                newAnalyticsID: 'save-now',
                newDaaLL: 'save-now-1',
            },
            browserParams: '#page=content&path=nala&query=',
            tags: '@mas-studio @ccd @ccd-edit @ccd-suggested @ccd-suggested-edit',
        },
    ],
};
