name: Check merge window
on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    check-time:
        runs-on: ubuntu-latest
        steps:
            - name: Check allowed merge hours
              run: |
                  HOUR=$(date -u +%H)  # UTC hour
                  if [ "$HOUR" -ge 15 ] || [ "$HOUR" -lt 6 ]; then
                    echo "Merges are blocked during 15UTC till 6UTC."
                    exit 1
                  else
                    echo "Merges are allowed."
                  fi
