name: IO WWW Merge
on:
  pull_request:
    types: [closed]
    paths:
      - 'io/www/**'

jobs:
  setup-tools:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install AIO CLI
      run: npm install -g @adobe/aio-cli

    - name: Install Playwright dependencies
      working-directory: nala/io
      run: npm install -D @playwright/test playwright

    - name: Install Playwright browsers
      working-directory: nala/io
      run: npx playwright install --with-deps

    - name: Upload AIO CLI
      uses: actions/upload-artifact@v4
      with:
        name: aio-cli-${{ github.run_id }}
        path: /usr/local

    - name: Upload Playwright
      uses: actions/upload-artifact@v4
      with:
        name: playwright-${{ github.run_id }}
        path: |
          ~/.cache/ms-playwright
          nala/io/node_modules

  build_and_test:
    needs: setup-tools
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: io/www
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        cache-dependency-path: io/www/package-lock.json

    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test

  deploy_stage:
    needs: [build_and_test, setup-tools]
    uses: ./.github/workflows/io-deploy.yaml
    secrets:
      workspace: ${{ secrets.AIO_NS_Stage }}
      auth: ${{ secrets.AIO_AUTH_Stage }}
      AIO_APIHOST: ${{ secrets.AIO_APIHOST }}
      AOS_API_KEY: ${{ secrets.AOS_API_KEY }}
      AOS_URL: ${{ secrets.AOS_URL }}
      ODIN_CDN_ENDPOINT: ${{ secrets.ODIN_CDN_ENDPOINT }}
      ODIN_ORIGIN_ENDPOINT: ${{ secrets.ODIN_ORIGIN_ENDPOINT }}
      OST_WRITE_API_KEY: ${{ secrets.OST_WRITE_API_KEY }}
      WCS_CDN_ENDPOINT: ${{ secrets.WCS_CDN_ENDPOINT }}
      WCS_ORIGIN_ENDPOINT: ${{ secrets.WCS_ORIGIN_ENDPOINT }}

  test_stage:
    needs: [deploy_stage, setup-tools]
    uses: ./.github/workflows/io-tests.yaml
    secrets:
      workspace: ${{ secrets.AIO_NS_Stage }}

  deploy_production:
    needs: [test_stage, setup-tools]
    uses: ./.github/workflows/io-deploy.yaml
    secrets:
      workspace: ${{ secrets.AIO_NS_PROD }}
      auth: ${{ secrets.AIO_AUTH_PROD }}
      AIO_APIHOST: ${{ secrets.AIO_APIHOST }}
      AOS_API_KEY: ${{ secrets.AOS_API_KEY }}
      AOS_URL: ${{ secrets.AOS_URL }}
      ODIN_CDN_ENDPOINT: ${{ secrets.ODIN_CDN_ENDPOINT }}
      ODIN_ORIGIN_ENDPOINT: ${{ secrets.ODIN_ORIGIN_ENDPOINT }}
      OST_WRITE_API_KEY: ${{ secrets.OST_WRITE_API_KEY }}
      WCS_CDN_ENDPOINT: ${{ secrets.WCS_CDN_ENDPOINT }}
      WCS_ORIGIN_ENDPOINT: ${{ secrets.WCS_ORIGIN_ENDPOINT }}

  test_production:
    needs: [deploy_production, setup-tools]
    uses: ./.github/workflows/io-tests.yaml
    secrets:
      workspace: ${{ secrets.AIO_NS_PROD }}
      