name: IO WWW PR Check
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'io/www/**'

jobs:
  setup-tools:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install Playwright dependencies
      working-directory: nala/io
      run: npm install -D @playwright/test playwright

    - name: Install Playwright browsers
      working-directory: nala/io
      run: npx playwright install --with-deps

    - name: Upload Playwright
      uses: actions/upload-artifact@v4
      with:
        name: playwright-${{ github.run_id }}
        path: |
          ~/.cache/ms-playwright
          nala/io/node_modules

  tests:
    needs: setup-tools
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: io/www
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        cache-dependency-path: io/www/package-lock.json

    - name: Install io/www dependencies
      run: npm ci
    
    - name: Run io/www tests
      run: npm test

  log-workspace:
    needs: [tests, setup-tools]
    if: success() && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Log Workspace Selection
      run: |
        if [ -n "${{ secrets[format('AIO_NS_{0}', github.actor)] }}" ]; then
          echo "Using author-specific workspace for ${{ github.actor }}"
        else
          echo "Falling back to QA workspace"
        fi

  deploy:
    needs: [tests, log-workspace, setup-tools]
    if: success() && github.event_name == 'pull_request'
    uses: ./.github/workflows/io-deploy.yaml
    secrets:
      workspace: ${{ secrets[format('AIO_NS_{0}', github.actor)] || secrets.AIO_NS_QA }}
      auth: ${{ secrets[format('AIO_AUTH_{0}', github.actor)] || secrets.AIO_AUTH_QA }}
      AIO_APIHOST: ${{ secrets.AIO_APIHOST }}
      AOS_API_KEY: ${{ secrets.AOS_API_KEY }}
      AOS_URL: ${{ secrets.AOS_URL }}
      ODIN_CDN_ENDPOINT: ${{ secrets.ODIN_CDN_ENDPOINT }}
      ODIN_ORIGIN_ENDPOINT: ${{ secrets.ODIN_ORIGIN_ENDPOINT }}
      OST_WRITE_API_KEY: ${{ secrets.OST_WRITE_API_KEY }}
      WCS_CDN_ENDPOINT: ${{ secrets.WCS_CDN_ENDPOINT }}
      WCS_ORIGIN_ENDPOINT: ${{ secrets.WCS_ORIGIN_ENDPOINT }}

  test-deployed:
    needs: [deploy, setup-tools]
    if: success() && github.event_name == 'pull_request'
    uses: ./.github/workflows/io-tests.yaml
    secrets:
      workspace: ${{ secrets[format('AIO_NS_{0}', github.actor)] || secrets.AIO_NS_QA }}
