name: IO WWW Fragment Client Integrity Check
on:
    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - 'io/www/**'
jobs:
    tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: io/www

        strategy:
            matrix:
                node-version: [22.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
                  cache-dependency-path: io/www/package.json

            - name: Install dependencies
              run: npm ci

            - name: Check fragment-client.js before build
              id: before-build
              run: |
                  if [ -f "studio/libs/fragment-client.js" ]; then
                    echo "before_hash=$(sha256sum studio/libs/fragment-client.js | cut -d' ' -f1)" >> $GITHUB_OUTPUT
                  else
                    echo "before_hash=file_not_found" >> $GITHUB_OUTPUT
                  fi

            - name: Build client
              run: npm run build:client

            - name: Check fragment-client.js after build
              id: after-build
              run: |
                  if [ -f "studio/libs/fragment-client.js" ]; then
                    echo "after_hash=$(sha256sum studio/libs/fragment-client.js | cut -d' ' -f1)" >> $GITHUB_OUTPUT
                  else
                    echo "after_hash=file_not_found" >> $GITHUB_OUTPUT
                  fi

            - name: Verify fragment-client.js integrity
              run: |
                  if [ "${{ steps.before-build.outputs.before_hash }}" != "${{ steps.after-build.outputs.after_hash }}" ]; then
                    echo "❌ fragment-client.js build should be part of that PR!"
                    echo "Before: ${{ steps.before-build.outputs.before_hash }}"
                    echo "After: ${{ steps.after-build.outputs.after_hash }}"
                    echo "This indicates that the client build process has modified the file."
                    echo "Please commit the updated fragment-client.js file."
                    exit 1
                  else
                    echo "✅ fragment-client.js integrity verified - no changes detected"
                  fi
