name: IO WWW Tests
on:
  workflow_call:
    secrets:
      workspace:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: io/www
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Download Playwright
      uses: actions/download-artifact@v4
      with:
        name: playwright-${{ github.run_id }}
        path: playwright-artifact
      continue-on-error: true

    - name: Setup Playwright
      run: |
        echo "Setting up Playwright..."
        
        # Create necessary directories
        mkdir -p ~/.cache/ms-playwright
        mkdir -p nala/io/node_modules
        
        # Check if artifact was downloaded successfully
        if [ -d "playwright-artifact" ]; then
          echo "Playwright artifact found, restoring from cache..."
          
          # Restore Playwright browsers
          if [ -d "playwright-artifact/.cache/ms-playwright" ]; then
            cp -r playwright-artifact/.cache/ms-playwright/* ~/.cache/ms-playwright/ 2>/dev/null || true
            echo "Playwright browsers restored"
          fi
          
          # Restore node_modules
          if [ -d "playwright-artifact/nala/io/node_modules" ]; then
            cp -r playwright-artifact/nala/io/node_modules/* nala/io/node_modules/ 2>/dev/null || true
            echo "Playwright dependencies restored"
          fi
          
          # Verify Playwright is available
          if command -v npx >/dev/null 2>&1 && npx playwright --version >/dev/null 2>&1; then
            echo "Playwright setup successful"
          else
            echo "Playwright verification failed, falling back to fresh install"
            cd nala/io && npm install -D @playwright/test playwright && npx playwright install --with-deps
          fi
        else
          echo "Playwright artifact not found, installing fresh..."
          cd nala/io && npm install -D @playwright/test playwright && npx playwright install --with-deps
        fi

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y xvfb

    - name: Verify test setup
      working-directory: nala/io
      run: |
        echo "Verifying test environment..."
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Playwright version: $(npx playwright --version)"
        echo "Available browsers:"
        npx playwright install --dry-run | grep -E "(chromium|firefox|webkit)" || true

    - name: Run Playwright Tests
      env:
        TEST_URL: https://stage--milo--adobecom.hlx.live/libs/features/mas/docs/ccd.html?mas-io-url=https://${{ secrets.workspace }}.adobeioruntime.net/api/v1/web/MerchAtScale
        HEALTH_CHECK_URL: https://${{ secrets.workspace }}.adobeioruntime.net/api/v1/web/MerchAtScale/health-check
      working-directory: nala/io
      run: |
        # Run health check test
        echo "Running health check test"
        npx playwright test ioAutomation.js --grep "@health" --config=playwright.config.js
        
        # Run default locale tests
        echo "Running default locale tests"
        xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npx playwright test ioAutomation.js --grep "@e2e" --config=playwright.config.js
        
        # Run French locale tests
        echo "Running French locale tests"
        TEST_URL="${TEST_URL}&locale=fr_FR" xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npx playwright test ioAutomation.js --grep "@e2e" --config=playwright.config.js
