name: Update OST Products

on:
  schedule:
    - cron: '0 8 * * *' # Daily at 8am UTC (9am CET), triggered on default branch = main
  workflow_dispatch:

jobs:
  update-products:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: run npm clean install 
      run: npm ci
     
    - name: Run getProductScript.mjs
      run: node studio/ost/scripts/getProductScript.mjs
      env:
        AOS_URL: ${{vars.AOS_URL}}
        AOS_API_KEY: ${{vars.AOS_API_KEY}}

    - name: Check & push changes in products.js
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "actions@github.com"
        if [ -n "$(git status --porcelain studio/ost/products.js)" ]; then
          git add studio/ost/products.js
          git commit -m "Update products.js file."
          git push
        else
          echo "No changes to commit."
        fi
