name: Run Nala on Milo Libs

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Provide the live branch url. ex: https://main--mas--adobecom.aem.live'
        required: false
        type: string
      milolibs:
        description: 'Provide MiloLibs param. ex: ?milolibs=stage--milo--adobecom'
        required: false
        type: string
      tags:
        description: 'Test scenario tags, if empty all tests will run. i.e., @mas-studio'
        required: false
        type: string
      platform:
        description: 'Platform to run tests on; select one, options: [ubuntu-latest, macos-latest]'
        required: true
        type: string

jobs:
  platform_matrix:
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]
    name: Running tests
    runs-on: ${{ inputs.platform }}
    env:
      WORKFLOW_NAME: 'Milo Libs Run'
      MILO_LIBS_RUN: 'true'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            **/package-lock.json
            **/yarn.lock

      - name: Set environment variables
        run: |
          echo "PR_BRANCH_MILOLIBS_LIVE_URL=${{ github.event.inputs.branch }}" >> $GITHUB_ENV
          echo "MILO_LIBS=${{ github.event.inputs.milolibs }}" >> $GITHUB_ENV

      - name: Run Nala ${{ inputs.platform }}
        uses: ./
        env:
          labels: ${{ inputs.tags }}
          IMS_EMAIL: ${{ secrets.IMS_EMAIL }}
          IMS_PASS: ${{ secrets.IMS_PASS }}        
      - name: Persist JSON Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nala-results
          path: nala-results.json
          retention-days: 30
