name: MAS Studio Monitor

on:
  schedule:
    - cron: "*/15 * * * *"   # Executes every 15 minutes
  workflow_dispatch:

# Prevent multiple runs from happening at the same time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  platform_matrix:
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]
    name: Running Studio Monitor Nala tests
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Prevent hanging jobs
    env:
      WORKFLOW_NAME: 'Studio Montor'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            **/package-lock.json
            **/yarn.lock

      - name: Set execute permission for monitor.sh
        run: chmod +x ./nala/utils/monitor.sh

      - name: Run Studio Monitor Nala tests with monitor.sh
        run: ./nala/utils/monitor.sh
        env:
          GITHUB_ACTION_PATH: ${{ github.workspace }}
          IMS_EMAIL: ${{ secrets.IMS_EMAIL }}
          IMS_PASS: ${{ secrets.IMS_PASS }}
      - name: Persist JSON Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nala-results
          path: nala-results.json
          retention-days: 30
